/*
 * File: send_MAVLink_v4_4_2_beta_3_HOME.c
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand, 
 *   you must change it only in the area defined as:  
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text' 
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  ------------------------------------------------------------------------- 
 *
 * Created: Fri Jul 19 14:38:19 2019
 */

#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME send_MAVLink_v4_4_2_beta_3_HOME
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS            35
/* Input Port  0 */
#define IN_PORT_0_NAME        iflogic
#define INPUT_0_WIDTH         1
#define INPUT_DIMS_0_COL      1
#define INPUT_0_DTYPE         uint8_T
#define INPUT_0_COMPLEX       COMPLEX_NO
#define IN_0_FRAME_BASED      FRAME_NO
#define IN_0_BUS_BASED        0
#define IN_0_BUS_NAME         
#define IN_0_DIMS             1-D
#define INPUT_0_FEEDTHROUGH   1
#define IN_0_ISSIGNED         0
#define IN_0_WORDLENGTH       8
#define IN_0_FIXPOINTSCALING  1
#define IN_0_FRACTIONLENGTH   9
#define IN_0_BIAS             0
#define IN_0_SLOPE            0.125
/* Input Port  1 */
#define IN_PORT_1_NAME        time_in
#define INPUT_1_WIDTH         1
#define INPUT_DIMS_1_COL      1
#define INPUT_1_DTYPE         uint32_T
#define INPUT_1_COMPLEX       COMPLEX_NO
#define IN_1_FRAME_BASED      FRAME_NO
#define IN_1_BUS_BASED        0
#define IN_1_BUS_NAME         
#define IN_1_DIMS             1-D
#define INPUT_1_FEEDTHROUGH   1
#define IN_1_ISSIGNED         0
#define IN_1_WORDLENGTH       8
#define IN_1_FIXPOINTSCALING  1
#define IN_1_FRACTIONLENGTH   9
#define IN_1_BIAS             0
#define IN_1_SLOPE            0.125
/* Input Port  2 */
#define IN_PORT_2_NAME        AP_SI
#define INPUT_2_WIDTH         1
#define INPUT_DIMS_2_COL      1
#define INPUT_2_DTYPE         uint8_T
#define INPUT_2_COMPLEX       COMPLEX_NO
#define IN_2_FRAME_BASED      FRAME_NO
#define IN_2_BUS_BASED        0
#define IN_2_BUS_NAME         
#define IN_2_DIMS             1-D
#define INPUT_2_FEEDTHROUGH   1
#define IN_2_ISSIGNED         0
#define IN_2_WORDLENGTH       8
#define IN_2_FIXPOINTSCALING  1
#define IN_2_FRACTIONLENGTH   9
#define IN_2_BIAS             0
#define IN_2_SLOPE            0.125
/* Input Port  3 */
#define IN_PORT_3_NAME        GC_req
#define INPUT_3_WIDTH         3
#define INPUT_DIMS_3_COL      1
#define INPUT_3_DTYPE         uint16_T
#define INPUT_3_COMPLEX       COMPLEX_NO
#define IN_3_FRAME_BASED      FRAME_NO
#define IN_3_BUS_BASED        0
#define IN_3_BUS_NAME         
#define IN_3_DIMS             1-D
#define INPUT_3_FEEDTHROUGH   1
#define IN_3_ISSIGNED         0
#define IN_3_WORDLENGTH       8
#define IN_3_FIXPOINTSCALING  1
#define IN_3_FRACTIONLENGTH   9
#define IN_3_BIAS             0
#define IN_3_SLOPE            0.125
/* Input Port  4 */
#define IN_PORT_4_NAME        P_val
#define INPUT_4_WIDTH         16
#define INPUT_DIMS_4_COL      1
#define INPUT_4_DTYPE         real32_T
#define INPUT_4_COMPLEX       COMPLEX_NO
#define IN_4_FRAME_BASED      FRAME_NO
#define IN_4_BUS_BASED        0
#define IN_4_BUS_NAME         
#define IN_4_DIMS             1-D
#define INPUT_4_FEEDTHROUGH   1
#define IN_4_ISSIGNED         0
#define IN_4_WORDLENGTH       8
#define IN_4_FIXPOINTSCALING  1
#define IN_4_FRACTIONLENGTH   9
#define IN_4_BIAS             0
#define IN_4_SLOPE            0.125
/* Input Port  5 */
#define IN_PORT_5_NAME        WP_info
#define INPUT_5_WIDTH         6
#define INPUT_DIMS_5_COL      1
#define INPUT_5_DTYPE         uint16_T
#define INPUT_5_COMPLEX       COMPLEX_NO
#define IN_5_FRAME_BASED      FRAME_NO
#define IN_5_BUS_BASED        0
#define IN_5_BUS_NAME         
#define IN_5_DIMS             1-D
#define INPUT_5_FEEDTHROUGH   1
#define IN_5_ISSIGNED         0
#define IN_5_WORDLENGTH       8
#define IN_5_FIXPOINTSCALING  1
#define IN_5_FRACTIONLENGTH   9
#define IN_5_BIAS             0
#define IN_5_SLOPE            0.125
/* Input Port  6 */
#define IN_PORT_6_NAME        WP_param
#define INPUT_6_WIDTH         7
#define INPUT_DIMS_6_COL      1
#define INPUT_6_DTYPE         real32_T
#define INPUT_6_COMPLEX       COMPLEX_NO
#define IN_6_FRAME_BASED      FRAME_NO
#define IN_6_BUS_BASED        0
#define IN_6_BUS_NAME         
#define IN_6_DIMS             1-D
#define INPUT_6_FEEDTHROUGH   1
#define IN_6_ISSIGNED         0
#define IN_6_WORDLENGTH       8
#define IN_6_FIXPOINTSCALING  1
#define IN_6_FRACTIONLENGTH   9
#define IN_6_BIAS             0
#define IN_6_SLOPE            0.125
/* Input Port  7 */
#define IN_PORT_7_NAME        ss_onboard
#define INPUT_7_WIDTH         3
#define INPUT_DIMS_7_COL      1
#define INPUT_7_DTYPE         uint32_T
#define INPUT_7_COMPLEX       COMPLEX_NO
#define IN_7_FRAME_BASED      FRAME_NO
#define IN_7_BUS_BASED        0
#define IN_7_BUS_NAME         
#define IN_7_DIMS             1-D
#define INPUT_7_FEEDTHROUGH   1
#define IN_7_ISSIGNED         0
#define IN_7_WORDLENGTH       8
#define IN_7_FIXPOINTSCALING  1
#define IN_7_FRACTIONLENGTH   9
#define IN_7_BIAS             0
#define IN_7_SLOPE            0.125
/* Input Port  8 */
#define IN_PORT_8_NAME        ss_LVDE
#define INPUT_8_WIDTH         8
#define INPUT_DIMS_8_COL      1
#define INPUT_8_DTYPE         uint16_T
#define INPUT_8_COMPLEX       COMPLEX_NO
#define IN_8_FRAME_BASED      FRAME_NO
#define IN_8_BUS_BASED        0
#define IN_8_BUS_NAME         
#define IN_8_DIMS             1-D
#define INPUT_8_FEEDTHROUGH   1
#define IN_8_ISSIGNED         0
#define IN_8_WORDLENGTH       8
#define IN_8_FIXPOINTSCALING  1
#define IN_8_FRACTIONLENGTH   9
#define IN_8_BIAS             0
#define IN_8_SLOPE            0.125
/* Input Port  9 */
#define IN_PORT_9_NAME        ss_C
#define INPUT_9_WIDTH         1
#define INPUT_DIMS_9_COL      1
#define INPUT_9_DTYPE         int16_T
#define INPUT_9_COMPLEX       COMPLEX_NO
#define IN_9_FRAME_BASED      FRAME_NO
#define IN_9_BUS_BASED        0
#define IN_9_BUS_NAME         
#define IN_9_DIMS             1-D
#define INPUT_9_FEEDTHROUGH   1
#define IN_9_ISSIGNED         0
#define IN_9_WORDLENGTH       8
#define IN_9_FIXPOINTSCALING  1
#define IN_9_FRACTIONLENGTH   9
#define IN_9_BIAS             0
#define IN_9_SLOPE            0.125
/* Input Port  10 */
#define IN_PORT_10_NAME        ss_R
#define INPUT_10_WIDTH         1
#define INPUT_DIMS_10_COL      1
#define INPUT_10_DTYPE         int8_T
#define INPUT_10_COMPLEX       COMPLEX_NO
#define IN_10_FRAME_BASED      FRAME_NO
#define IN_10_BUS_BASED        0
#define IN_10_BUS_NAME         
#define IN_10_DIMS             1-D
#define INPUT_10_FEEDTHROUGH   1
#define IN_10_ISSIGNED         0
#define IN_10_WORDLENGTH       8
#define IN_10_FIXPOINTSCALING  1
#define IN_10_FRACTIONLENGTH   9
#define IN_10_BIAS             0
#define IN_10_SLOPE            0.125
/* Input Port  11 */
#define IN_PORT_11_NAME        Heartbeat_custom
#define INPUT_11_WIDTH         1
#define INPUT_DIMS_11_COL      1
#define INPUT_11_DTYPE         uint32_T
#define INPUT_11_COMPLEX       COMPLEX_NO
#define IN_11_FRAME_BASED      FRAME_NO
#define IN_11_BUS_BASED        0
#define IN_11_BUS_NAME         
#define IN_11_DIMS             1-D
#define INPUT_11_FEEDTHROUGH   1
#define IN_11_ISSIGNED         0
#define IN_11_WORDLENGTH       8
#define IN_11_FIXPOINTSCALING  1
#define IN_11_FRACTIONLENGTH   9
#define IN_11_BIAS             0
#define IN_11_SLOPE            0.125
/* Input Port  12 */
#define IN_PORT_12_NAME        Heartbeat_data
#define INPUT_12_WIDTH         4
#define INPUT_DIMS_12_COL      1
#define INPUT_12_DTYPE         uint8_T
#define INPUT_12_COMPLEX       COMPLEX_NO
#define IN_12_FRAME_BASED      FRAME_NO
#define IN_12_BUS_BASED        0
#define IN_12_BUS_NAME         
#define IN_12_DIMS             1-D
#define INPUT_12_FEEDTHROUGH   1
#define IN_12_ISSIGNED         0
#define IN_12_WORDLENGTH       8
#define IN_12_FIXPOINTSCALING  1
#define IN_12_FRACTIONLENGTH   9
#define IN_12_BIAS             0
#define IN_12_SLOPE            0.125
/* Input Port  13 */
#define IN_PORT_13_NAME        IMU_data
#define INPUT_13_WIDTH         9
#define INPUT_DIMS_13_COL      1
#define INPUT_13_DTYPE         int16_T
#define INPUT_13_COMPLEX       COMPLEX_NO
#define IN_13_FRAME_BASED      FRAME_NO
#define IN_13_BUS_BASED        0
#define IN_13_BUS_NAME         
#define IN_13_DIMS             1-D
#define INPUT_13_FEEDTHROUGH   1
#define IN_13_ISSIGNED         0
#define IN_13_WORDLENGTH       8
#define IN_13_FIXPOINTSCALING  1
#define IN_13_FRACTIONLENGTH   9
#define IN_13_BIAS             0
#define IN_13_SLOPE            0.125
/* Input Port  14 */
#define IN_PORT_14_NAME        attitude
#define INPUT_14_WIDTH         6
#define INPUT_DIMS_14_COL      1
#define INPUT_14_DTYPE         real32_T
#define INPUT_14_COMPLEX       COMPLEX_NO
#define IN_14_FRAME_BASED      FRAME_NO
#define IN_14_BUS_BASED        0
#define IN_14_BUS_NAME         
#define IN_14_DIMS             1-D
#define INPUT_14_FEEDTHROUGH   1
#define IN_14_ISSIGNED         0
#define IN_14_WORDLENGTH       8
#define IN_14_FIXPOINTSCALING  1
#define IN_14_FRACTIONLENGTH   9
#define IN_14_BIAS             0
#define IN_14_SLOPE            0.125
/* Input Port  15 */
#define IN_PORT_15_NAME        lat_long_alt
#define INPUT_15_WIDTH         4
#define INPUT_DIMS_15_COL      1
#define INPUT_15_DTYPE         int32_T
#define INPUT_15_COMPLEX       COMPLEX_NO
#define IN_15_FRAME_BASED      FRAME_NO
#define IN_15_BUS_BASED        0
#define IN_15_BUS_NAME         
#define IN_15_DIMS             1-D
#define INPUT_15_FEEDTHROUGH   1
#define IN_15_ISSIGNED         0
#define IN_15_WORDLENGTH       8
#define IN_15_FIXPOINTSCALING  1
#define IN_15_FRACTIONLENGTH   9
#define IN_15_BIAS             0
#define IN_15_SLOPE            0.125
/* Input Port  16 */
#define IN_PORT_16_NAME        velGPS
#define INPUT_16_WIDTH         3
#define INPUT_DIMS_16_COL      1
#define INPUT_16_DTYPE         int16_T
#define INPUT_16_COMPLEX       COMPLEX_NO
#define IN_16_FRAME_BASED      FRAME_NO
#define IN_16_BUS_BASED        0
#define IN_16_BUS_NAME         
#define IN_16_DIMS             1-D
#define INPUT_16_FEEDTHROUGH   1
#define IN_16_ISSIGNED         0
#define IN_16_WORDLENGTH       8
#define IN_16_FIXPOINTSCALING  1
#define IN_16_FRACTIONLENGTH   9
#define IN_16_BIAS             0
#define IN_16_SLOPE            0.125
/* Input Port  17 */
#define IN_PORT_17_NAME        hdg
#define INPUT_17_WIDTH         1
#define INPUT_DIMS_17_COL      1
#define INPUT_17_DTYPE         uint16_T
#define INPUT_17_COMPLEX       COMPLEX_NO
#define IN_17_FRAME_BASED      FRAME_NO
#define IN_17_BUS_BASED        0
#define IN_17_BUS_NAME         
#define IN_17_DIMS             1-D
#define INPUT_17_FEEDTHROUGH   1
#define IN_17_ISSIGNED         0
#define IN_17_WORDLENGTH       8
#define IN_17_FIXPOINTSCALING  1
#define IN_17_FRACTIONLENGTH   9
#define IN_17_BIAS             0
#define IN_17_SLOPE            0.125
/* Input Port  18 */
#define IN_PORT_18_NAME        VFR_speed
#define INPUT_18_WIDTH         4
#define INPUT_DIMS_18_COL      1
#define INPUT_18_DTYPE         real32_T
#define INPUT_18_COMPLEX       COMPLEX_NO
#define IN_18_FRAME_BASED      FRAME_NO
#define IN_18_BUS_BASED        0
#define IN_18_BUS_NAME         
#define IN_18_DIMS             1-D
#define INPUT_18_FEEDTHROUGH   1
#define IN_18_ISSIGNED         0
#define IN_18_WORDLENGTH       8
#define IN_18_FIXPOINTSCALING  1
#define IN_18_FRACTIONLENGTH   9
#define IN_18_BIAS             0
#define IN_18_SLOPE            0.125
/* Input Port  19 */
#define IN_PORT_19_NAME        VFR_H
#define INPUT_19_WIDTH         1
#define INPUT_DIMS_19_COL      1
#define INPUT_19_DTYPE         int16_T
#define INPUT_19_COMPLEX       COMPLEX_NO
#define IN_19_FRAME_BASED      FRAME_NO
#define IN_19_BUS_BASED        0
#define IN_19_BUS_NAME         
#define IN_19_DIMS             1-D
#define INPUT_19_FEEDTHROUGH   1
#define IN_19_ISSIGNED         0
#define IN_19_WORDLENGTH       8
#define IN_19_FIXPOINTSCALING  1
#define IN_19_FRACTIONLENGTH   9
#define IN_19_BIAS             0
#define IN_19_SLOPE            0.125
/* Input Port  20 */
#define IN_PORT_20_NAME        VFR_T
#define INPUT_20_WIDTH         1
#define INPUT_DIMS_20_COL      1
#define INPUT_20_DTYPE         uint16_T
#define INPUT_20_COMPLEX       COMPLEX_NO
#define IN_20_FRAME_BASED      FRAME_NO
#define IN_20_BUS_BASED        0
#define IN_20_BUS_NAME         
#define IN_20_DIMS             1-D
#define INPUT_20_FEEDTHROUGH   1
#define IN_20_ISSIGNED         0
#define IN_20_WORDLENGTH       8
#define IN_20_FIXPOINTSCALING  1
#define IN_20_FRACTIONLENGTH   9
#define IN_20_BIAS             0
#define IN_20_SLOPE            0.125
/* Input Port  21 */
#define IN_PORT_21_NAME        Ser_data
#define INPUT_21_WIDTH         9
#define INPUT_DIMS_21_COL      1
#define INPUT_21_DTYPE         uint16_T
#define INPUT_21_COMPLEX       COMPLEX_NO
#define IN_21_FRAME_BASED      FRAME_NO
#define IN_21_BUS_BASED        0
#define IN_21_BUS_NAME         
#define IN_21_DIMS             1-D
#define INPUT_21_FEEDTHROUGH   1
#define IN_21_ISSIGNED         0
#define IN_21_WORDLENGTH       8
#define IN_21_FIXPOINTSCALING  1
#define IN_21_FRACTIONLENGTH   9
#define IN_21_BIAS             0
#define IN_21_SLOPE            0.125
/* Input Port  22 */
#define IN_PORT_22_NAME        prior_in
#define INPUT_22_WIDTH         1
#define INPUT_DIMS_22_COL      1
#define INPUT_22_DTYPE         uint16_T
#define INPUT_22_COMPLEX       COMPLEX_NO
#define IN_22_FRAME_BASED      FRAME_NO
#define IN_22_BUS_BASED        0
#define IN_22_BUS_NAME         
#define IN_22_DIMS             1-D
#define INPUT_22_FEEDTHROUGH   1
#define IN_22_ISSIGNED         0
#define IN_22_WORDLENGTH       8
#define IN_22_FIXPOINTSCALING  1
#define IN_22_FRACTIONLENGTH   9
#define IN_22_BIAS             0
#define IN_22_SLOPE            0.125
/* Input Port  23 */
#define IN_PORT_23_NAME        P_refer
#define INPUT_23_WIDTH         1
#define INPUT_DIMS_23_COL      1
#define INPUT_23_DTYPE         real32_T
#define INPUT_23_COMPLEX       COMPLEX_NO
#define IN_23_FRAME_BASED      FRAME_NO
#define IN_23_BUS_BASED        0
#define IN_23_BUS_NAME         
#define IN_23_DIMS             1-D
#define INPUT_23_FEEDTHROUGH   1
#define IN_23_ISSIGNED         0
#define IN_23_WORDLENGTH       8
#define IN_23_FIXPOINTSCALING  1
#define IN_23_FRACTIONLENGTH   9
#define IN_23_BIAS             0
#define IN_23_SLOPE            0.125
/* Input Port  24 */
#define IN_PORT_24_NAME        Cal_alt
#define INPUT_24_WIDTH         1
#define INPUT_DIMS_24_COL      1
#define INPUT_24_DTYPE         uint8_T
#define INPUT_24_COMPLEX       COMPLEX_NO
#define IN_24_FRAME_BASED      FRAME_NO
#define IN_24_BUS_BASED        0
#define IN_24_BUS_NAME         
#define IN_24_DIMS             1-D
#define INPUT_24_FEEDTHROUGH   1
#define IN_24_ISSIGNED         0
#define IN_24_WORDLENGTH       8
#define IN_24_FIXPOINTSCALING  1
#define IN_24_FRACTIONLENGTH   9
#define IN_24_BIAS             0
#define IN_24_SLOPE            0.125
/* Input Port  25 */
#define IN_PORT_25_NAME        T_0
#define INPUT_25_WIDTH         1
#define INPUT_DIMS_25_COL      1
#define INPUT_25_DTYPE         real32_T
#define INPUT_25_COMPLEX       COMPLEX_NO
#define IN_25_FRAME_BASED      FRAME_NO
#define IN_25_BUS_BASED        0
#define IN_25_BUS_NAME         
#define IN_25_DIMS             1-D
#define INPUT_25_FEEDTHROUGH   1
#define IN_25_ISSIGNED         0
#define IN_25_WORDLENGTH       8
#define IN_25_FIXPOINTSCALING  1
#define IN_25_FRACTIONLENGTH   9
#define IN_25_BIAS             0
#define IN_25_SLOPE            0.125
/* Input Port  26 */
#define IN_PORT_26_NAME        T_int
#define INPUT_26_WIDTH         1
#define INPUT_DIMS_26_COL      1
#define INPUT_26_DTYPE         uint8_T
#define INPUT_26_COMPLEX       COMPLEX_NO
#define IN_26_FRAME_BASED      FRAME_NO
#define IN_26_BUS_BASED        0
#define IN_26_BUS_NAME         
#define IN_26_DIMS             1-D
#define INPUT_26_FEEDTHROUGH   1
#define IN_26_ISSIGNED         0
#define IN_26_WORDLENGTH       8
#define IN_26_FIXPOINTSCALING  1
#define IN_26_FRACTIONLENGTH   9
#define IN_26_BIAS             0
#define IN_26_SLOPE            0.125
/* Input Port  27 */
#define IN_PORT_27_NAME        P_RAW
#define INPUT_27_WIDTH         1
#define INPUT_DIMS_27_COL      1
#define INPUT_27_DTYPE         real32_T
#define INPUT_27_COMPLEX       COMPLEX_NO
#define IN_27_FRAME_BASED      FRAME_NO
#define IN_27_BUS_BASED        0
#define IN_27_BUS_NAME         
#define IN_27_DIMS             1-D
#define INPUT_27_FEEDTHROUGH   1
#define IN_27_ISSIGNED         0
#define IN_27_WORDLENGTH       8
#define IN_27_FIXPOINTSCALING  1
#define IN_27_FRACTIONLENGTH   9
#define IN_27_BIAS             0
#define IN_27_SLOPE            0.125
/* Input Port  28 */
#define IN_PORT_28_NAME        deltaP_RAW
#define INPUT_28_WIDTH         1
#define INPUT_DIMS_28_COL      1
#define INPUT_28_DTYPE         real32_T
#define INPUT_28_COMPLEX       COMPLEX_NO
#define IN_28_FRAME_BASED      FRAME_NO
#define IN_28_BUS_BASED        0
#define IN_28_BUS_NAME         
#define IN_28_DIMS             1-D
#define INPUT_28_FEEDTHROUGH   1
#define IN_28_ISSIGNED         0
#define IN_28_WORDLENGTH       8
#define IN_28_FIXPOINTSCALING  1
#define IN_28_FRACTIONLENGTH   9
#define IN_28_BIAS             0
#define IN_28_SLOPE            0.125
/* Input Port  29 */
#define IN_PORT_29_NAME        AB_T
#define INPUT_29_WIDTH         1
#define INPUT_DIMS_29_COL      1
#define INPUT_29_DTYPE         int16_T
#define INPUT_29_COMPLEX       COMPLEX_NO
#define IN_29_FRAME_BASED      FRAME_NO
#define IN_29_BUS_BASED        0
#define IN_29_BUS_NAME         
#define IN_29_DIMS             1-D
#define INPUT_29_FEEDTHROUGH   1
#define IN_29_ISSIGNED         0
#define IN_29_WORDLENGTH       8
#define IN_29_FIXPOINTSCALING  1
#define IN_29_FRACTIONLENGTH   9
#define IN_29_BIAS             0
#define IN_29_SLOPE            0.125
/* Input Port  30 */
#define IN_PORT_30_NAME        Cal_home
#define INPUT_30_WIDTH         3
#define INPUT_DIMS_30_COL      1
#define INPUT_30_DTYPE         uint8_T
#define INPUT_30_COMPLEX       COMPLEX_NO
#define IN_30_FRAME_BASED      FRAME_NO
#define IN_30_BUS_BASED        0
#define IN_30_BUS_NAME         
#define IN_30_DIMS             1-D
#define INPUT_30_FEEDTHROUGH   1
#define IN_30_ISSIGNED         0
#define IN_30_WORDLENGTH       8
#define IN_30_FIXPOINTSCALING  1
#define IN_30_FRACTIONLENGTH   9
#define IN_30_BIAS             0
#define IN_30_SLOPE            0.125
/* Input Port  31 */
#define IN_PORT_31_NAME        H_LAT
#define INPUT_31_WIDTH         1
#define INPUT_DIMS_31_COL      1
#define INPUT_31_DTYPE         real_T
#define INPUT_31_COMPLEX       COMPLEX_NO
#define IN_31_FRAME_BASED      FRAME_NO
#define IN_31_BUS_BASED        0
#define IN_31_BUS_NAME         
#define IN_31_DIMS             1-D
#define INPUT_31_FEEDTHROUGH   1
#define IN_31_ISSIGNED         0
#define IN_31_WORDLENGTH       8
#define IN_31_FIXPOINTSCALING  1
#define IN_31_FRACTIONLENGTH   9
#define IN_31_BIAS             0
#define IN_31_SLOPE            0.125
/* Input Port  32 */
#define IN_PORT_32_NAME        H_LONG
#define INPUT_32_WIDTH         1
#define INPUT_DIMS_32_COL      1
#define INPUT_32_DTYPE         real_T
#define INPUT_32_COMPLEX       COMPLEX_NO
#define IN_32_FRAME_BASED      FRAME_NO
#define IN_32_BUS_BASED        0
#define IN_32_BUS_NAME         
#define IN_32_DIMS             1-D
#define INPUT_32_FEEDTHROUGH   1
#define IN_32_ISSIGNED         0
#define IN_32_WORDLENGTH       8
#define IN_32_FIXPOINTSCALING  1
#define IN_32_FRACTIONLENGTH   9
#define IN_32_BIAS             0
#define IN_32_SLOPE            0.125
/* Input Port  33 */
#define IN_PORT_33_NAME        H_ALT
#define INPUT_33_WIDTH         1
#define INPUT_DIMS_33_COL      1
#define INPUT_33_DTYPE         real_T
#define INPUT_33_COMPLEX       COMPLEX_NO
#define IN_33_FRAME_BASED      FRAME_NO
#define IN_33_BUS_BASED        0
#define IN_33_BUS_NAME         
#define IN_33_DIMS             1-D
#define INPUT_33_FEEDTHROUGH   1
#define IN_33_ISSIGNED         0
#define IN_33_WORDLENGTH       8
#define IN_33_FIXPOINTSCALING  1
#define IN_33_FRACTIONLENGTH   9
#define IN_33_BIAS             0
#define IN_33_SLOPE            0.125
/* Input Port  34 */
#define IN_PORT_34_NAME        h_lidar
#define INPUT_34_WIDTH         1
#define INPUT_DIMS_34_COL      1
#define INPUT_34_DTYPE         uint16_T
#define INPUT_34_COMPLEX       COMPLEX_NO
#define IN_34_FRAME_BASED      FRAME_NO
#define IN_34_BUS_BASED        0
#define IN_34_BUS_NAME         
#define IN_34_DIMS             1-D
#define INPUT_34_FEEDTHROUGH   1
#define IN_34_ISSIGNED         0
#define IN_34_WORDLENGTH       8
#define IN_34_FIXPOINTSCALING  1
#define IN_34_FRACTIONLENGTH   9
#define IN_34_BIAS             0
#define IN_34_SLOPE            0.125

#define NUM_OUTPUTS           4
/* Output Port  0 */
#define OUT_PORT_0_NAME       enable
#define OUTPUT_0_WIDTH        1
#define OUTPUT_DIMS_0_COL     1
#define OUTPUT_0_DTYPE        uint8_T
#define OUTPUT_0_COMPLEX      COMPLEX_NO
#define OUT_0_FRAME_BASED     FRAME_NO
#define OUT_0_BUS_BASED       0
#define OUT_0_BUS_NAME        
#define OUT_0_DIMS            1-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125
/* Output Port  1 */
#define OUT_PORT_1_NAME       msg_out
#define OUTPUT_1_WIDTH        264
#define OUTPUT_DIMS_1_COL     1
#define OUTPUT_1_DTYPE        uint8_T
#define OUTPUT_1_COMPLEX      COMPLEX_NO
#define OUT_1_FRAME_BASED     FRAME_NO
#define OUT_1_BUS_BASED       0
#define OUT_1_BUS_NAME        
#define OUT_1_DIMS            1-D
#define OUT_1_ISSIGNED        1
#define OUT_1_WORDLENGTH      8
#define OUT_1_FIXPOINTSCALING 1
#define OUT_1_FRACTIONLENGTH  3
#define OUT_1_BIAS            0
#define OUT_1_SLOPE           0.125
/* Output Port  2 */
#define OUT_PORT_2_NAME       Len
#define OUTPUT_2_WIDTH        1
#define OUTPUT_DIMS_2_COL     1
#define OUTPUT_2_DTYPE        uint16_T
#define OUTPUT_2_COMPLEX      COMPLEX_NO
#define OUT_2_FRAME_BASED     FRAME_NO
#define OUT_2_BUS_BASED       0
#define OUT_2_BUS_NAME        
#define OUT_2_DIMS            1-D
#define OUT_2_ISSIGNED        1
#define OUT_2_WORDLENGTH      8
#define OUT_2_FIXPOINTSCALING 1
#define OUT_2_FRACTIONLENGTH  3
#define OUT_2_BIAS            0
#define OUT_2_SLOPE           0.125
/* Output Port  3 */
#define OUT_PORT_3_NAME       prior_out
#define OUTPUT_3_WIDTH        1
#define OUTPUT_DIMS_3_COL     1
#define OUTPUT_3_DTYPE        uint16_T
#define OUTPUT_3_COMPLEX      COMPLEX_NO
#define OUT_3_FRAME_BASED     FRAME_NO
#define OUT_3_BUS_BASED       0
#define OUT_3_BUS_NAME        
#define OUT_3_DIMS            1-D
#define OUT_3_ISSIGNED        1
#define OUT_3_WORDLENGTH      8
#define OUT_3_FIXPOINTSCALING 1
#define OUT_3_FRACTIONLENGTH  3
#define OUT_3_BIAS            0
#define OUT_3_SLOPE           0.125

#define NPARAMS               0

#define SAMPLE_TIME_0         INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES       0
#define DISC_STATES_IC        [0]
#define NUM_CONT_STATES       0
#define CONT_STATES_IC        [0]

#define SFUNWIZ_GENERATE_TLC  1
#define SOURCEFILES           "__SFB__"
#define PANELINDEX            8
#define USE_SIMSTRUCT         0
#define SHOW_COMPILE_STEPS    0
#define CREATE_DEBUG_MEXFILE  0
#define SAVE_CODE_ONLY        0
#define SFUNWIZ_REVISION      3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"


extern void send_MAVLink_v4_4_2_beta_3_HOME_Outputs_wrapper(const uint8_T *iflogic,
			const uint32_T *time_in,
			const uint8_T *AP_SI,
			const uint16_T *GC_req,
			const real32_T *P_val,
			const uint16_T *WP_info,
			const real32_T *WP_param,
			const uint32_T *ss_onboard,
			const uint16_T *ss_LVDE,
			const int16_T *ss_C,
			const int8_T *ss_R,
			const uint32_T *Heartbeat_custom,
			const uint8_T *Heartbeat_data,
			const int16_T *IMU_data,
			const real32_T *attitude,
			const int32_T *lat_long_alt,
			const int16_T *velGPS,
			const uint16_T *hdg,
			const real32_T *VFR_speed,
			const int16_T *VFR_H,
			const uint16_T *VFR_T,
			const uint16_T *Ser_data,
			const uint16_T *prior_in,
			const real32_T *P_refer,
			const uint8_T *Cal_alt,
			const real32_T *T_0,
			const uint8_T *T_int,
			const real32_T *P_RAW,
			const real32_T *deltaP_RAW,
			const int16_T *AB_T,
			const uint8_T *Cal_home,
			const real_T *H_LAT,
			const real_T *H_LONG,
			const real_T *H_ALT,
			const uint16_T *h_lidar,
			uint8_T *enable,
			uint8_T *msg_out,
			uint16_T *Len,
			uint16_T *prior_out);
/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{

    DECL_AND_INIT_DIMSINFO(inputDimsInfo);
    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return; /* Parameter mismatch will be reported by Simulink */
    }

    ssSetArrayLayoutForCodeGen(S, SS_COLUMN_MAJOR);

    ssSetSimStateCompliance(S, USE_DEFAULT_SIM_STATE);

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);


    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;
    /* Input Port 0 */
    ssSetInputPortWidth(S, 0, INPUT_0_WIDTH);
    ssSetInputPortDataType(S, 0, SS_UINT8);
    ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 0, 1); /*direct input signal access*/

    /* Input Port 1 */
    ssSetInputPortWidth(S, 1, INPUT_1_WIDTH);
    ssSetInputPortDataType(S, 1, SS_UINT32);
    ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 1, 1); /*direct input signal access*/

    /* Input Port 2 */
    ssSetInputPortWidth(S, 2, INPUT_2_WIDTH);
    ssSetInputPortDataType(S, 2, SS_UINT8);
    ssSetInputPortComplexSignal(S, 2, INPUT_2_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 2, 1); /*direct input signal access*/

    /* Input Port 3 */
    ssSetInputPortWidth(S, 3, INPUT_3_WIDTH);
    ssSetInputPortDataType(S, 3, SS_UINT16);
    ssSetInputPortComplexSignal(S, 3, INPUT_3_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 3, INPUT_3_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 3, 1); /*direct input signal access*/

    /* Input Port 4 */
    ssSetInputPortWidth(S, 4, INPUT_4_WIDTH);
    ssSetInputPortDataType(S, 4, SS_SINGLE);
    ssSetInputPortComplexSignal(S, 4, INPUT_4_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 4, INPUT_4_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 4, 1); /*direct input signal access*/

    /* Input Port 5 */
    ssSetInputPortWidth(S, 5, INPUT_5_WIDTH);
    ssSetInputPortDataType(S, 5, SS_UINT16);
    ssSetInputPortComplexSignal(S, 5, INPUT_5_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 5, INPUT_5_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 5, 1); /*direct input signal access*/

    /* Input Port 6 */
    ssSetInputPortWidth(S, 6, INPUT_6_WIDTH);
    ssSetInputPortDataType(S, 6, SS_SINGLE);
    ssSetInputPortComplexSignal(S, 6, INPUT_6_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 6, INPUT_6_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 6, 1); /*direct input signal access*/

    /* Input Port 7 */
    ssSetInputPortWidth(S, 7, INPUT_7_WIDTH);
    ssSetInputPortDataType(S, 7, SS_UINT32);
    ssSetInputPortComplexSignal(S, 7, INPUT_7_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 7, INPUT_7_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 7, 1); /*direct input signal access*/

    /* Input Port 8 */
    ssSetInputPortWidth(S, 8, INPUT_8_WIDTH);
    ssSetInputPortDataType(S, 8, SS_UINT16);
    ssSetInputPortComplexSignal(S, 8, INPUT_8_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 8, INPUT_8_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 8, 1); /*direct input signal access*/

    /* Input Port 9 */
    ssSetInputPortWidth(S, 9, INPUT_9_WIDTH);
    ssSetInputPortDataType(S, 9, SS_INT16);
    ssSetInputPortComplexSignal(S, 9, INPUT_9_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 9, INPUT_9_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 9, 1); /*direct input signal access*/

    /* Input Port 10 */
    ssSetInputPortWidth(S, 10, INPUT_10_WIDTH);
    ssSetInputPortDataType(S, 10, SS_INT8);
    ssSetInputPortComplexSignal(S, 10, INPUT_10_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 10, INPUT_10_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 10, 1); /*direct input signal access*/

    /* Input Port 11 */
    ssSetInputPortWidth(S, 11, INPUT_11_WIDTH);
    ssSetInputPortDataType(S, 11, SS_UINT32);
    ssSetInputPortComplexSignal(S, 11, INPUT_11_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 11, INPUT_11_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 11, 1); /*direct input signal access*/

    /* Input Port 12 */
    ssSetInputPortWidth(S, 12, INPUT_12_WIDTH);
    ssSetInputPortDataType(S, 12, SS_UINT8);
    ssSetInputPortComplexSignal(S, 12, INPUT_12_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 12, INPUT_12_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 12, 1); /*direct input signal access*/

    /* Input Port 13 */
    ssSetInputPortWidth(S, 13, INPUT_13_WIDTH);
    ssSetInputPortDataType(S, 13, SS_INT16);
    ssSetInputPortComplexSignal(S, 13, INPUT_13_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 13, INPUT_13_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 13, 1); /*direct input signal access*/

    /* Input Port 14 */
    ssSetInputPortWidth(S, 14, INPUT_14_WIDTH);
    ssSetInputPortDataType(S, 14, SS_SINGLE);
    ssSetInputPortComplexSignal(S, 14, INPUT_14_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 14, INPUT_14_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 14, 1); /*direct input signal access*/

    /* Input Port 15 */
    ssSetInputPortWidth(S, 15, INPUT_15_WIDTH);
    ssSetInputPortDataType(S, 15, SS_INT32);
    ssSetInputPortComplexSignal(S, 15, INPUT_15_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 15, INPUT_15_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 15, 1); /*direct input signal access*/

    /* Input Port 16 */
    ssSetInputPortWidth(S, 16, INPUT_16_WIDTH);
    ssSetInputPortDataType(S, 16, SS_INT16);
    ssSetInputPortComplexSignal(S, 16, INPUT_16_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 16, INPUT_16_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 16, 1); /*direct input signal access*/

    /* Input Port 17 */
    ssSetInputPortWidth(S, 17, INPUT_17_WIDTH);
    ssSetInputPortDataType(S, 17, SS_UINT16);
    ssSetInputPortComplexSignal(S, 17, INPUT_17_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 17, INPUT_17_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 17, 1); /*direct input signal access*/

    /* Input Port 18 */
    ssSetInputPortWidth(S, 18, INPUT_18_WIDTH);
    ssSetInputPortDataType(S, 18, SS_SINGLE);
    ssSetInputPortComplexSignal(S, 18, INPUT_18_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 18, INPUT_18_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 18, 1); /*direct input signal access*/

    /* Input Port 19 */
    ssSetInputPortWidth(S, 19, INPUT_19_WIDTH);
    ssSetInputPortDataType(S, 19, SS_INT16);
    ssSetInputPortComplexSignal(S, 19, INPUT_19_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 19, INPUT_19_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 19, 1); /*direct input signal access*/

    /* Input Port 20 */
    ssSetInputPortWidth(S, 20, INPUT_20_WIDTH);
    ssSetInputPortDataType(S, 20, SS_UINT16);
    ssSetInputPortComplexSignal(S, 20, INPUT_20_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 20, INPUT_20_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 20, 1); /*direct input signal access*/

    /* Input Port 21 */
    ssSetInputPortWidth(S, 21, INPUT_21_WIDTH);
    ssSetInputPortDataType(S, 21, SS_UINT16);
    ssSetInputPortComplexSignal(S, 21, INPUT_21_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 21, INPUT_21_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 21, 1); /*direct input signal access*/

    /* Input Port 22 */
    ssSetInputPortWidth(S, 22, INPUT_22_WIDTH);
    ssSetInputPortDataType(S, 22, SS_UINT16);
    ssSetInputPortComplexSignal(S, 22, INPUT_22_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 22, INPUT_22_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 22, 1); /*direct input signal access*/

    /* Input Port 23 */
    ssSetInputPortWidth(S, 23, INPUT_23_WIDTH);
    ssSetInputPortDataType(S, 23, SS_SINGLE);
    ssSetInputPortComplexSignal(S, 23, INPUT_23_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 23, INPUT_23_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 23, 1); /*direct input signal access*/

    /* Input Port 24 */
    ssSetInputPortWidth(S, 24, INPUT_24_WIDTH);
    ssSetInputPortDataType(S, 24, SS_UINT8);
    ssSetInputPortComplexSignal(S, 24, INPUT_24_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 24, INPUT_24_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 24, 1); /*direct input signal access*/

    /* Input Port 25 */
    ssSetInputPortWidth(S, 25, INPUT_25_WIDTH);
    ssSetInputPortDataType(S, 25, SS_SINGLE);
    ssSetInputPortComplexSignal(S, 25, INPUT_25_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 25, INPUT_25_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 25, 1); /*direct input signal access*/

    /* Input Port 26 */
    ssSetInputPortWidth(S, 26, INPUT_26_WIDTH);
    ssSetInputPortDataType(S, 26, SS_UINT8);
    ssSetInputPortComplexSignal(S, 26, INPUT_26_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 26, INPUT_26_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 26, 1); /*direct input signal access*/

    /* Input Port 27 */
    ssSetInputPortWidth(S, 27, INPUT_27_WIDTH);
    ssSetInputPortDataType(S, 27, SS_SINGLE);
    ssSetInputPortComplexSignal(S, 27, INPUT_27_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 27, INPUT_27_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 27, 1); /*direct input signal access*/

    /* Input Port 28 */
    ssSetInputPortWidth(S, 28, INPUT_28_WIDTH);
    ssSetInputPortDataType(S, 28, SS_SINGLE);
    ssSetInputPortComplexSignal(S, 28, INPUT_28_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 28, INPUT_28_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 28, 1); /*direct input signal access*/

    /* Input Port 29 */
    ssSetInputPortWidth(S, 29, INPUT_29_WIDTH);
    ssSetInputPortDataType(S, 29, SS_INT16);
    ssSetInputPortComplexSignal(S, 29, INPUT_29_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 29, INPUT_29_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 29, 1); /*direct input signal access*/

    /* Input Port 30 */
    ssSetInputPortWidth(S, 30, INPUT_30_WIDTH);
    ssSetInputPortDataType(S, 30, SS_UINT8);
    ssSetInputPortComplexSignal(S, 30, INPUT_30_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 30, INPUT_30_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 30, 1); /*direct input signal access*/

    /* Input Port 31 */
    ssSetInputPortWidth(S, 31, INPUT_31_WIDTH);
    ssSetInputPortDataType(S, 31, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 31, INPUT_31_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 31, INPUT_31_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 31, 1); /*direct input signal access*/

    /* Input Port 32 */
    ssSetInputPortWidth(S, 32, INPUT_32_WIDTH);
    ssSetInputPortDataType(S, 32, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 32, INPUT_32_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 32, INPUT_32_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 32, 1); /*direct input signal access*/

    /* Input Port 33 */
    ssSetInputPortWidth(S, 33, INPUT_33_WIDTH);
    ssSetInputPortDataType(S, 33, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 33, INPUT_33_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 33, INPUT_33_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 33, 1); /*direct input signal access*/

    /* Input Port 34 */
    ssSetInputPortWidth(S, 34, INPUT_34_WIDTH);
    ssSetInputPortDataType(S, 34, SS_UINT16);
    ssSetInputPortComplexSignal(S, 34, INPUT_34_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 34, INPUT_34_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 34, 1); /*direct input signal access*/


    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    /* Output Port 0 */
    ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
    ssSetOutputPortDataType(S, 0, SS_UINT8);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
    /* Output Port 1 */
    ssSetOutputPortWidth(S, 1, OUTPUT_1_WIDTH);
    ssSetOutputPortDataType(S, 1, SS_UINT8);
    ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);
    /* Output Port 2 */
    ssSetOutputPortWidth(S, 2, OUTPUT_2_WIDTH);
    ssSetOutputPortDataType(S, 2, SS_UINT16);
    ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);
    /* Output Port 3 */
    ssSetOutputPortWidth(S, 3, OUTPUT_3_WIDTH);
    ssSetOutputPortDataType(S, 3, SS_UINT16);
    ssSetOutputPortComplexSignal(S, 3, OUTPUT_3_COMPLEX);
    ssSetNumPWork(S, 0);

    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    ssSetSimulinkVersionGeneratedIn(S, "9.2");

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                     SS_OPTION_USE_TLC_WITH_ACCELERATOR |
                     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetModelReferenceSampleTimeDefaultInheritance(S);
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE
static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
    ssSetInputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_START  /* Change to #undef to remove function */
#if defined(MDL_START)
/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
}
#endif /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
    const uint8_T *iflogic = (uint8_T *) ssGetInputPortRealSignal(S, 0);
    const uint32_T *time_in = (uint32_T *) ssGetInputPortRealSignal(S, 1);
    const uint8_T *AP_SI = (uint8_T *) ssGetInputPortRealSignal(S, 2);
    const uint16_T *GC_req = (uint16_T *) ssGetInputPortRealSignal(S, 3);
    const real32_T *P_val = (real32_T *) ssGetInputPortRealSignal(S, 4);
    const uint16_T *WP_info = (uint16_T *) ssGetInputPortRealSignal(S, 5);
    const real32_T *WP_param = (real32_T *) ssGetInputPortRealSignal(S, 6);
    const uint32_T *ss_onboard = (uint32_T *) ssGetInputPortRealSignal(S, 7);
    const uint16_T *ss_LVDE = (uint16_T *) ssGetInputPortRealSignal(S, 8);
    const int16_T *ss_C = (int16_T *) ssGetInputPortRealSignal(S, 9);
    const int8_T *ss_R = (int8_T *) ssGetInputPortRealSignal(S, 10);
    const uint32_T *Heartbeat_custom = (uint32_T *) ssGetInputPortRealSignal(S, 11);
    const uint8_T *Heartbeat_data = (uint8_T *) ssGetInputPortRealSignal(S, 12);
    const int16_T *IMU_data = (int16_T *) ssGetInputPortRealSignal(S, 13);
    const real32_T *attitude = (real32_T *) ssGetInputPortRealSignal(S, 14);
    const int32_T *lat_long_alt = (int32_T *) ssGetInputPortRealSignal(S, 15);
    const int16_T *velGPS = (int16_T *) ssGetInputPortRealSignal(S, 16);
    const uint16_T *hdg = (uint16_T *) ssGetInputPortRealSignal(S, 17);
    const real32_T *VFR_speed = (real32_T *) ssGetInputPortRealSignal(S, 18);
    const int16_T *VFR_H = (int16_T *) ssGetInputPortRealSignal(S, 19);
    const uint16_T *VFR_T = (uint16_T *) ssGetInputPortRealSignal(S, 20);
    const uint16_T *Ser_data = (uint16_T *) ssGetInputPortRealSignal(S, 21);
    const uint16_T *prior_in = (uint16_T *) ssGetInputPortRealSignal(S, 22);
    const real32_T *P_refer = (real32_T *) ssGetInputPortRealSignal(S, 23);
    const uint8_T *Cal_alt = (uint8_T *) ssGetInputPortRealSignal(S, 24);
    const real32_T *T_0 = (real32_T *) ssGetInputPortRealSignal(S, 25);
    const uint8_T *T_int = (uint8_T *) ssGetInputPortRealSignal(S, 26);
    const real32_T *P_RAW = (real32_T *) ssGetInputPortRealSignal(S, 27);
    const real32_T *deltaP_RAW = (real32_T *) ssGetInputPortRealSignal(S, 28);
    const int16_T *AB_T = (int16_T *) ssGetInputPortRealSignal(S, 29);
    const uint8_T *Cal_home = (uint8_T *) ssGetInputPortRealSignal(S, 30);
    const real_T *H_LAT = (real_T *) ssGetInputPortRealSignal(S, 31);
    const real_T *H_LONG = (real_T *) ssGetInputPortRealSignal(S, 32);
    const real_T *H_ALT = (real_T *) ssGetInputPortRealSignal(S, 33);
    const uint16_T *h_lidar = (uint16_T *) ssGetInputPortRealSignal(S, 34);
    uint8_T *enable = (uint8_T *) ssGetOutputPortRealSignal(S, 0);
    uint8_T *msg_out = (uint8_T *) ssGetOutputPortRealSignal(S, 1);
    uint16_T *Len = (uint16_T *) ssGetOutputPortRealSignal(S, 2);
    uint16_T *prior_out = (uint16_T *) ssGetOutputPortRealSignal(S, 3);

    send_MAVLink_v4_4_2_beta_3_HOME_Outputs_wrapper(iflogic, time_in, AP_SI, GC_req, P_val, WP_info, WP_param, ss_onboard, ss_LVDE, ss_C, ss_R, Heartbeat_custom, Heartbeat_data, IMU_data, attitude, lat_long_alt, velGPS, hdg, VFR_speed, VFR_H, VFR_T, Ser_data, prior_in, P_refer, Cal_alt, T_0, T_int, P_RAW, deltaP_RAW, AB_T, Cal_home, H_LAT, H_LONG, H_ALT, h_lidar, enable, msg_out, Len, prior_out);

}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{

}


#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif



