/*
 * File: Signal_Logger_sfun.c
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand, 
 *   you must change it only in the area defined as:  
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text' 
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  ------------------------------------------------------------------------- 
 *
 * Created: Wed Mar 08 19:41:14 2023
 */

#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME Signal_Logger_sfun
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS            2
/* Input Port  0 */
#define IN_PORT_0_NAME        flightData
#define INPUT_0_WIDTH         1
#define INPUT_DIMS_0_COL      1
#define INPUT_0_DTYPE         real_T
#define INPUT_0_COMPLEX       COMPLEX_NO
#define IN_0_FRAME_BASED      FRAME_NO
#define IN_0_BUS_BASED        1
#define IN_0_BUS_NAME         BUS_log_t
#define IN_0_DIMS             1-D
#define INPUT_0_FEEDTHROUGH   1
#define IN_0_ISSIGNED         0
#define IN_0_WORDLENGTH       8
#define IN_0_FIXPOINTSCALING  1
#define IN_0_FRACTIONLENGTH   9
#define IN_0_BIAS             0
#define IN_0_SLOPE            0.125
/* Input Port  1 */
#define IN_PORT_1_NAME        sec_flag
#define INPUT_1_WIDTH         1
#define INPUT_DIMS_1_COL      1
#define INPUT_1_DTYPE         boolean_T
#define INPUT_1_COMPLEX       COMPLEX_NO
#define IN_1_FRAME_BASED      FRAME_NO
#define IN_1_BUS_BASED        0
#define IN_1_BUS_NAME         
#define IN_1_DIMS             1-D
#define INPUT_1_FEEDTHROUGH   1
#define IN_1_ISSIGNED         0
#define IN_1_WORDLENGTH       8
#define IN_1_FIXPOINTSCALING  1
#define IN_1_FRACTIONLENGTH   9
#define IN_1_BIAS             0
#define IN_1_SLOPE            0.125

#define NUM_OUTPUTS           0

#define NPARAMS               0

#define SAMPLE_TIME_0         INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES       0
#define DISC_STATES_IC        [0]
#define NUM_CONT_STATES       0
#define CONT_STATES_IC        [0]

#define SFUNWIZ_GENERATE_TLC  1
#define SOURCEFILES           "__SFB__INC_PATH src"
#define PANELINDEX            N/A
#define USE_SIMSTRUCT         0
#define SHOW_COMPILE_STEPS    0
#define CREATE_DEBUG_MEXFILE  0
#define SAVE_CODE_ONLY        0
#define SFUNWIZ_REVISION      3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#include "Signal_Logger_sfun_bus.h"
/*
 * Code Generation Environment flag (simulation or standalone target).
 */
 static int_T isSimulationTarget;
/* Utility function prototypes. */
static int_T GetRTWEnvironmentMode(SimStruct *S);
/* Macro used to check if Simulation mode is set to accelerator */
#define isBusDWorkPresent  ( ( ( !ssRTWGenIsCodeGen(S) || isSimulationTarget ) && !ssIsExternalSim(S) ) || ssIsRapidAcceleratorActive(S) )

typedef struct {
    int_T offset;
    int_T elemSize;
    int_T numElems;
} busInfoStruct;

extern void Signal_Logger_sfun_Start_wrapper(void);
extern void Signal_Logger_sfun_Outputs_wrapper(const BUS_log_t *flightData,
			const boolean_T *sec_flag);
/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{

    DECL_AND_INIT_DIMSINFO(inputDimsInfo);
    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return; /* Parameter mismatch will be reported by Simulink */
    }

    ssSetArrayLayoutForCodeGen(S, SS_COLUMN_MAJOR);

    ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);


    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;
    /* Input Port 0 */

  /* Register BUS_log_t datatype for Input port 0 */

    #if defined(MATLAB_MEX_FILE)
    if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY)
    {
      DTypeId dataTypeIdReg;
      ssRegisterTypeFromNamedObject(S, "BUS_log_t", &dataTypeIdReg);
      if(dataTypeIdReg == INVALID_DTYPE_ID) return;
      ssSetInputPortDataType(S, 0, dataTypeIdReg);
    }
    #endif
    ssSetInputPortWidth(S, 0, INPUT_0_WIDTH);
    ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 0, 1); /*direct input signal access*/
    ssSetBusInputAsStruct(S, 0, IN_0_BUS_BASED);
    ssSetInputPortBusMode(S, 0, SL_BUS_MODE);
    /* Input Port 1 */
    ssSetInputPortWidth(S, 1, INPUT_1_WIDTH);
    ssSetInputPortDataType(S, 1, SS_BOOLEAN);
    ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 1, 1); /*direct input signal access*/


    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;

    if (ssRTWGenIsCodeGen(S)) {
        isSimulationTarget = GetRTWEnvironmentMode(S);
        if (isSimulationTarget == -1) {
            ssSetErrorStatus(S, " Unable to determine a valid code generation environment mode");
            return;
        }
        isSimulationTarget |= ssRTWGenIsModelReferenceSimTarget(S);
    }
    
    /* Set the number of dworks */
    if (!isBusDWorkPresent) {
        if (!ssSetNumDWork(S, 0)) return;
    } else {
        if (!ssSetNumDWork(S, 1)) return;
    }

    if (isBusDWorkPresent) {

      /*
       * Configure the dwork 0 (flightDataBUS)
       */
#if defined(MATLAB_MEX_FILE)
      if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
        DTypeId dataTypeIdReg;
        ssRegisterTypeFromNamedObject(S, "BUS_log_t", &dataTypeIdReg);
        if (dataTypeIdReg == INVALID_DTYPE_ID) return;
        ssSetDWorkDataType(S, 0, dataTypeIdReg);
      }
#endif
      
      ssSetDWorkUsageType(S, 0, SS_DWORK_USED_AS_DWORK);
      ssSetDWorkName(S, 0, "flightDataBUS");
      ssSetDWorkWidth(S, 0, DYNAMICALLY_SIZED);
      ssSetDWorkComplexSignal(S, 0, COMPLEX_NO);
    }
    ssSetNumPWork(S, 0);

    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    ssSetSimulinkVersionGeneratedIn(S, "10.2");

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                     SS_OPTION_USE_TLC_WITH_ACCELERATOR |
                     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetModelReferenceSampleTimeDefaultInheritance(S);
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE
static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
    ssSetInputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_SET_WORK_WIDTHS
#if defined(MDL_SET_WORK_WIDTHS) && defined(MATLAB_MEX_FILE)

static void mdlSetWorkWidths(SimStruct *S)
{
/* Set the width of DWork(s) used for marshalling the IOs */
    if (isBusDWorkPresent) {

        /* Update dwork 0 */
        ssSetDWorkWidth(S, 0, ssGetInputPortWidth(S, 0));

    }

}

#endif

#define MDL_START  /* Change to #undef to remove function */
#if defined(MDL_START)
/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
    /* Bus Information */
    slDataTypeAccess *dta = ssGetDataTypeAccess(S);
    const char *bpath = ssGetPath(S);
	DTypeId BUS_bool_log_tId = ssGetDataTypeId(S, "BUS_bool_log_t");
	DTypeId BUS_double_log_tId = ssGetDataTypeId(S, "BUS_double_log_t");
	DTypeId BUS_int16_log_tId = ssGetDataTypeId(S, "BUS_int16_log_t");
	DTypeId BUS_int32_log_tId = ssGetDataTypeId(S, "BUS_int32_log_t");
	DTypeId BUS_int8_log_tId = ssGetDataTypeId(S, "BUS_int8_log_t");
	DTypeId BUS_log_tId = ssGetDataTypeId(S, "BUS_log_t");
	DTypeId BUS_single_log_tId = ssGetDataTypeId(S, "BUS_single_log_t");
	DTypeId BUS_uint16_log_tId = ssGetDataTypeId(S, "BUS_uint16_log_t");
	DTypeId BUS_uint32_log_tId = ssGetDataTypeId(S, "BUS_uint32_log_t");
	DTypeId BUS_uint8_log_tId = ssGetDataTypeId(S, "BUS_uint8_log_t");

	busInfoStruct *busInfo = (busInfoStruct *)malloc(98*sizeof(busInfoStruct));
	if(busInfo==NULL) {
        ssSetErrorStatus(S, "Memory allocation failure");
        return;
    }

      /* Calculate offsets of all primitive elements of the bus */

	busInfo[0].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 0) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_double_log_tId, 0);
	busInfo[0].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[0].numElems = 1;
	busInfo[1].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 0) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_double_log_tId, 1);
	busInfo[1].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[1].numElems = 1;
	busInfo[2].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 0) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_double_log_tId, 2);
	busInfo[2].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[2].numElems = 1;
	busInfo[3].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 0) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_double_log_tId, 3);
	busInfo[3].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[3].numElems = 1;
	busInfo[4].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 0) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_double_log_tId, 4);
	busInfo[4].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[4].numElems = 1;
	busInfo[5].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 0);
	busInfo[5].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[5].numElems = 1;
	busInfo[6].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 1);
	busInfo[6].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[6].numElems = 1;
	busInfo[7].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 2);
	busInfo[7].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[7].numElems = 1;
	busInfo[8].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 3);
	busInfo[8].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[8].numElems = 1;
	busInfo[9].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 4);
	busInfo[9].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[9].numElems = 1;
	busInfo[10].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 5);
	busInfo[10].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[10].numElems = 1;
	busInfo[11].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 6);
	busInfo[11].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[11].numElems = 1;
	busInfo[12].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 7);
	busInfo[12].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[12].numElems = 1;
	busInfo[13].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 8);
	busInfo[13].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[13].numElems = 1;
	busInfo[14].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 9);
	busInfo[14].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[14].numElems = 1;
	busInfo[15].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 10);
	busInfo[15].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[15].numElems = 1;
	busInfo[16].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 11);
	busInfo[16].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[16].numElems = 1;
	busInfo[17].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 12);
	busInfo[17].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[17].numElems = 1;
	busInfo[18].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 13);
	busInfo[18].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[18].numElems = 1;
	busInfo[19].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 14);
	busInfo[19].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[19].numElems = 1;
	busInfo[20].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 15);
	busInfo[20].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[20].numElems = 1;
	busInfo[21].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 16);
	busInfo[21].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[21].numElems = 1;
	busInfo[22].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 17);
	busInfo[22].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[22].numElems = 1;
	busInfo[23].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 18);
	busInfo[23].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[23].numElems = 1;
	busInfo[24].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 19);
	busInfo[24].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[24].numElems = 1;
	busInfo[25].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 20);
	busInfo[25].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[25].numElems = 1;
	busInfo[26].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 21);
	busInfo[26].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[26].numElems = 1;
	busInfo[27].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 22);
	busInfo[27].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[27].numElems = 1;
	busInfo[28].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 1) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_single_log_tId, 23);
	busInfo[28].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "single"));
	busInfo[28].numElems = 1;
	busInfo[29].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 2) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_int32_log_tId, 0);
	busInfo[29].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "int32"));
	busInfo[29].numElems = 1;
	busInfo[30].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 2) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_int32_log_tId, 1);
	busInfo[30].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "int32"));
	busInfo[30].numElems = 1;
	busInfo[31].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 3) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_uint32_log_tId, 0);
	busInfo[31].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "uint32"));
	busInfo[31].numElems = 1;
	busInfo[32].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 3) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_uint32_log_tId, 1);
	busInfo[32].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "uint32"));
	busInfo[32].numElems = 1;
	busInfo[33].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 4) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_int16_log_tId, 0);
	busInfo[33].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "int16"));
	busInfo[33].numElems = 1;
	busInfo[34].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 4) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_int16_log_tId, 1);
	busInfo[34].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "int16"));
	busInfo[34].numElems = 1;
	busInfo[35].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 4) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_int16_log_tId, 2);
	busInfo[35].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "int16"));
	busInfo[35].numElems = 1;
	busInfo[36].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 4) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_int16_log_tId, 3);
	busInfo[36].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "int16"));
	busInfo[36].numElems = 1;
	busInfo[37].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 4) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_int16_log_tId, 4);
	busInfo[37].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "int16"));
	busInfo[37].numElems = 1;
	busInfo[38].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 4) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_int16_log_tId, 5);
	busInfo[38].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "int16"));
	busInfo[38].numElems = 1;
	busInfo[39].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 4) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_int16_log_tId, 6);
	busInfo[39].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "int16"));
	busInfo[39].numElems = 1;
	busInfo[40].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 4) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_int16_log_tId, 7);
	busInfo[40].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "int16"));
	busInfo[40].numElems = 1;
	busInfo[41].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 5) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_uint16_log_tId, 0);
	busInfo[41].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "uint16"));
	busInfo[41].numElems = 1;
	busInfo[42].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 5) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_uint16_log_tId, 1);
	busInfo[42].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "uint16"));
	busInfo[42].numElems = 1;
	busInfo[43].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 6) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_int8_log_tId, 0);
	busInfo[43].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "int8"));
	busInfo[43].numElems = 1;
	busInfo[44].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 6) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_int8_log_tId, 1);
	busInfo[44].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "int8"));
	busInfo[44].numElems = 1;
	busInfo[45].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 7) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_uint8_log_tId, 0);
	busInfo[45].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "uint8"));
	busInfo[45].numElems = 1;
	busInfo[46].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 7) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_uint8_log_tId, 1);
	busInfo[46].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "uint8"));
	busInfo[46].numElems = 1;
	busInfo[47].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 8) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_bool_log_tId, 0);
	busInfo[47].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "boolean"));
	busInfo[47].numElems = 1;
	busInfo[48].offset   = dtaGetDataTypeElementOffset(dta, bpath, BUS_log_tId, 8) + \
							dtaGetDataTypeElementOffset(dta, bpath, BUS_bool_log_tId, 1);
	busInfo[48].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "boolean"));
	busInfo[48].numElems = 1;
	ssSetUserData(S, busInfo);

    Signal_Logger_sfun_Start_wrapper();
}
#endif /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
    const char *flightData = (char *) ssGetInputPortSignal(S, 0);
    const boolean_T *sec_flag = (boolean_T *) ssGetInputPortRealSignal(S, 1);

	busInfoStruct* busInfo = (busInfoStruct *) ssGetUserData(S);

	/* Temporary bus copy declarations */
	BUS_log_t _flightDataBUS;

	/* Copy input bus into temporary structure */
	(void) memcpy(&_flightDataBUS.double_data.time_frame, flightData + busInfo[0].offset, busInfo[0].elemSize * busInfo[0].numElems);
	(void) memcpy(&_flightDataBUS.double_data.Lat_raw, flightData + busInfo[1].offset, busInfo[1].elemSize * busInfo[1].numElems);
	(void) memcpy(&_flightDataBUS.double_data.Long_raw, flightData + busInfo[2].offset, busInfo[2].elemSize * busInfo[2].numElems);
	(void) memcpy(&_flightDataBUS.double_data.Lat, flightData + busInfo[3].offset, busInfo[3].elemSize * busInfo[3].numElems);
	(void) memcpy(&_flightDataBUS.double_data.Long, flightData + busInfo[4].offset, busInfo[4].elemSize * busInfo[4].numElems);
	(void) memcpy(&_flightDataBUS.single_data.v_gps_raw, flightData + busInfo[5].offset, busInfo[5].elemSize * busInfo[5].numElems);
	(void) memcpy(&_flightDataBUS.single_data.h_gps_raw, flightData + busInfo[6].offset, busInfo[6].elemSize * busInfo[6].numElems);
	(void) memcpy(&_flightDataBUS.single_data.heading_raw, flightData + busInfo[7].offset, busInfo[7].elemSize * busInfo[7].numElems);
	(void) memcpy(&_flightDataBUS.single_data.acc_x_raw, flightData + busInfo[8].offset, busInfo[8].elemSize * busInfo[8].numElems);
	(void) memcpy(&_flightDataBUS.single_data.acc_y_raw, flightData + busInfo[9].offset, busInfo[9].elemSize * busInfo[9].numElems);
	(void) memcpy(&_flightDataBUS.single_data.acc_z_raw, flightData + busInfo[10].offset, busInfo[10].elemSize * busInfo[10].numElems);
	(void) memcpy(&_flightDataBUS.single_data.p_raw, flightData + busInfo[11].offset, busInfo[11].elemSize * busInfo[11].numElems);
	(void) memcpy(&_flightDataBUS.single_data.q_raw, flightData + busInfo[12].offset, busInfo[12].elemSize * busInfo[12].numElems);
	(void) memcpy(&_flightDataBUS.single_data.r_raw, flightData + busInfo[13].offset, busInfo[13].elemSize * busInfo[13].numElems);
	(void) memcpy(&_flightDataBUS.single_data.phi_raw, flightData + busInfo[14].offset, busInfo[14].elemSize * busInfo[14].numElems);
	(void) memcpy(&_flightDataBUS.single_data.theta_raw, flightData + busInfo[15].offset, busInfo[15].elemSize * busInfo[15].numElems);
	(void) memcpy(&_flightDataBUS.single_data.psi_raw, flightData + busInfo[16].offset, busInfo[16].elemSize * busInfo[16].numElems);
	(void) memcpy(&_flightDataBUS.single_data.v_pitot_raw, flightData + busInfo[17].offset, busInfo[17].elemSize * busInfo[17].numElems);
	(void) memcpy(&_flightDataBUS.single_data.dist_lidar_raw, flightData + busInfo[18].offset, busInfo[18].elemSize * busInfo[18].numElems);
	(void) memcpy(&_flightDataBUS.single_data.h_baro_raw, flightData + busInfo[19].offset, busInfo[19].elemSize * busInfo[19].numElems);
	(void) memcpy(&_flightDataBUS.single_data.press_raw, flightData + busInfo[20].offset, busInfo[20].elemSize * busInfo[20].numElems);
	(void) memcpy(&_flightDataBUS.single_data.temp_raw, flightData + busInfo[21].offset, busInfo[21].elemSize * busInfo[21].numElems);
	(void) memcpy(&_flightDataBUS.single_data.h_baro_filt, flightData + busInfo[22].offset, busInfo[22].elemSize * busInfo[22].numElems);
	(void) memcpy(&_flightDataBUS.single_data.ias_filt, flightData + busInfo[23].offset, busInfo[23].elemSize * busInfo[23].numElems);
	(void) memcpy(&_flightDataBUS.single_data.RC_filt, flightData + busInfo[24].offset, busInfo[24].elemSize * busInfo[24].numElems);
	(void) memcpy(&_flightDataBUS.single_data.groundspeed_filt, flightData + busInfo[25].offset, busInfo[25].elemSize * busInfo[25].numElems);
	(void) memcpy(&_flightDataBUS.single_data.heading_filt, flightData + busInfo[26].offset, busInfo[26].elemSize * busInfo[26].numElems);
	(void) memcpy(&_flightDataBUS.single_data.dist_lidar_filt, flightData + busInfo[27].offset, busInfo[27].elemSize * busInfo[27].numElems);
	(void) memcpy(&_flightDataBUS.single_data.dp_raw, flightData + busInfo[28].offset, busInfo[28].elemSize * busInfo[28].numElems);
	(void) memcpy(&_flightDataBUS.int32_data.dummy3, flightData + busInfo[29].offset, busInfo[29].elemSize * busInfo[29].numElems);
	(void) memcpy(&_flightDataBUS.int32_data.dummy4, flightData + busInfo[30].offset, busInfo[30].elemSize * busInfo[30].numElems);
	(void) memcpy(&_flightDataBUS.uint32_data.dummy5, flightData + busInfo[31].offset, busInfo[31].elemSize * busInfo[31].numElems);
	(void) memcpy(&_flightDataBUS.uint32_data.dummy6, flightData + busInfo[32].offset, busInfo[32].elemSize * busInfo[32].numElems);
	(void) memcpy(&_flightDataBUS.int16_data.manual_throttleCmd_pwm, flightData + busInfo[33].offset, busInfo[33].elemSize * busInfo[33].numElems);
	(void) memcpy(&_flightDataBUS.int16_data.manual_elevatorCmd_pwm, flightData + busInfo[34].offset, busInfo[34].elemSize * busInfo[34].numElems);
	(void) memcpy(&_flightDataBUS.int16_data.manual_aileronCmd_pwm, flightData + busInfo[35].offset, busInfo[35].elemSize * busInfo[35].numElems);
	(void) memcpy(&_flightDataBUS.int16_data.manual_rudderCmd_pwm, flightData + busInfo[36].offset, busInfo[36].elemSize * busInfo[36].numElems);
	(void) memcpy(&_flightDataBUS.int16_data.throttleCmd_pwm, flightData + busInfo[37].offset, busInfo[37].elemSize * busInfo[37].numElems);
	(void) memcpy(&_flightDataBUS.int16_data.elevatorCmd_pwm, flightData + busInfo[38].offset, busInfo[38].elemSize * busInfo[38].numElems);
	(void) memcpy(&_flightDataBUS.int16_data.aileronCmd_pwm, flightData + busInfo[39].offset, busInfo[39].elemSize * busInfo[39].numElems);
	(void) memcpy(&_flightDataBUS.int16_data.rudderCmd_pwm, flightData + busInfo[40].offset, busInfo[40].elemSize * busInfo[40].numElems);
	(void) memcpy(&_flightDataBUS.uint16_data.dummy9, flightData + busInfo[41].offset, busInfo[41].elemSize * busInfo[41].numElems);
	(void) memcpy(&_flightDataBUS.uint16_data.dummy10, flightData + busInfo[42].offset, busInfo[42].elemSize * busInfo[42].numElems);
	(void) memcpy(&_flightDataBUS.int8_data.dummy11, flightData + busInfo[43].offset, busInfo[43].elemSize * busInfo[43].numElems);
	(void) memcpy(&_flightDataBUS.int8_data.dummy12, flightData + busInfo[44].offset, busInfo[44].elemSize * busInfo[44].numElems);
	(void) memcpy(&_flightDataBUS.uint8_data.gps_fix, flightData + busInfo[45].offset, busInfo[45].elemSize * busInfo[45].numElems);
	(void) memcpy(&_flightDataBUS.uint8_data.dummy12, flightData + busInfo[46].offset, busInfo[46].elemSize * busInfo[46].numElems);
	(void) memcpy(&_flightDataBUS.bool_data.dummy15, flightData + busInfo[47].offset, busInfo[47].elemSize * busInfo[47].numElems);
	(void) memcpy(&_flightDataBUS.bool_data.dummy16, flightData + busInfo[48].offset, busInfo[48].elemSize * busInfo[48].numElems);

    Signal_Logger_sfun_Outputs_wrapper(&_flightDataBUS, sec_flag);

	/* Copy temporary structure into output bus */

}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
    /* Free stored bus information */
    busInfoStruct *busInfo = (busInfoStruct *) ssGetUserData(S);
    if(busInfo != NULL) {
        free(busInfo);
    }

}

static int_T GetRTWEnvironmentMode(SimStruct *S)
{
    int_T status = -1;
    mxArray *plhs[1];
    mxArray *prhs[1];
    mxArray * err;
    
    /*
     * Get the name of the Simulink block diagram
     */
    prhs[0] = mxCreateString(ssGetModelName(ssGetRootSS(S)));
    plhs[0] = NULL;
    
    /*
     * Call "isSimulationTarget = rtwenvironmentmode(modelName)" in MATLAB
     */
    err = mexCallMATLABWithTrap(1, plhs, 1, prhs, "rtwenvironmentmode");
    mxDestroyArray(prhs[0]);
    
    /*
     * Set the error status if an error occurred
     */
    if (err) {
        if (plhs[0]) {
            mxDestroyArray(plhs[0]);
            plhs[0] = NULL;
        }
        ssSetErrorStatus(S, "Unknown error during call to 'rtwenvironmentmode'.");
        return -1;
    }
    
    /*
     * Get the value returned by rtwenvironmentmode(modelName)
    */
    if (plhs[0]) {
        status = (int_T) (mxGetScalar(plhs[0]) != 0);
        mxDestroyArray(plhs[0]);
        plhs[0] = NULL;
    }
    
    return (status);
}

#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif



