/*
 * File: receive_MAVLink_v4_6_beta_AL_HITL_HOME_sfun.c
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand, 
 *   you must change it only in the area defined as:  
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text' 
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  ------------------------------------------------------------------------- 
 *
 * Created: Thu May 11 18:18:20 2023
 */

#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME receive_MAVLink_v4_6_beta_AL_HITL_HOME_sfun
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS            8
/* Input Port  0 */
#define IN_PORT_0_NAME        bytes_in
#define INPUT_0_WIDTH         DYNAMICALLY_SIZED
#define INPUT_DIMS_0_COL      1
#define INPUT_0_DTYPE         uint8_T
#define INPUT_0_COMPLEX       COMPLEX_NO
#define IN_0_FRAME_BASED      FRAME_NO
#define IN_0_BUS_BASED        0
#define IN_0_BUS_NAME         
#define IN_0_DIMS             1-D
#define INPUT_0_FEEDTHROUGH   1
#define IN_0_ISSIGNED         0
#define IN_0_WORDLENGTH       8
#define IN_0_FIXPOINTSCALING  1
#define IN_0_FRACTIONLENGTH   9
#define IN_0_BIAS             0
#define IN_0_SLOPE            0.125
/* Input Port  1 */
#define IN_PORT_1_NAME        len_in
#define INPUT_1_WIDTH         1
#define INPUT_DIMS_1_COL      1
#define INPUT_1_DTYPE         int32_T
#define INPUT_1_COMPLEX       COMPLEX_NO
#define IN_1_FRAME_BASED      FRAME_NO
#define IN_1_BUS_BASED        0
#define IN_1_BUS_NAME         
#define IN_1_DIMS             1-D
#define INPUT_1_FEEDTHROUGH   1
#define IN_1_ISSIGNED         0
#define IN_1_WORDLENGTH       8
#define IN_1_FIXPOINTSCALING  1
#define IN_1_FRACTIONLENGTH   9
#define IN_1_BIAS             0
#define IN_1_SLOPE            0.125
/* Input Port  2 */
#define IN_PORT_2_NAME        count
#define INPUT_2_WIDTH         1
#define INPUT_DIMS_2_COL      1
#define INPUT_2_DTYPE         uint16_T
#define INPUT_2_COMPLEX       COMPLEX_NO
#define IN_2_FRAME_BASED      FRAME_NO
#define IN_2_BUS_BASED        0
#define IN_2_BUS_NAME         
#define IN_2_DIMS             1-D
#define INPUT_2_FEEDTHROUGH   1
#define IN_2_ISSIGNED         0
#define IN_2_WORDLENGTH       8
#define IN_2_FIXPOINTSCALING  1
#define IN_2_FRACTIONLENGTH   9
#define IN_2_BIAS             0
#define IN_2_SLOPE            0.125
/* Input Port  3 */
#define IN_PORT_3_NAME        AP_SI
#define INPUT_3_WIDTH         1
#define INPUT_DIMS_3_COL      1
#define INPUT_3_DTYPE         uint8_T
#define INPUT_3_COMPLEX       COMPLEX_NO
#define IN_3_FRAME_BASED      FRAME_NO
#define IN_3_BUS_BASED        0
#define IN_3_BUS_NAME         
#define IN_3_DIMS             1-D
#define INPUT_3_FEEDTHROUGH   1
#define IN_3_ISSIGNED         0
#define IN_3_WORDLENGTH       8
#define IN_3_FIXPOINTSCALING  1
#define IN_3_FRACTIONLENGTH   9
#define IN_3_BIAS             0
#define IN_3_SLOPE            0.125
/* Input Port  4 */
#define IN_PORT_4_NAME        mem_in
#define INPUT_4_WIDTH         8
#define INPUT_DIMS_4_COL      1
#define INPUT_4_DTYPE         uint16_T
#define INPUT_4_COMPLEX       COMPLEX_NO
#define IN_4_FRAME_BASED      FRAME_NO
#define IN_4_BUS_BASED        0
#define IN_4_BUS_NAME         
#define IN_4_DIMS             1-D
#define INPUT_4_FEEDTHROUGH   1
#define IN_4_ISSIGNED         0
#define IN_4_WORDLENGTH       8
#define IN_4_FIXPOINTSCALING  1
#define IN_4_FRACTIONLENGTH   9
#define IN_4_BIAS             0
#define IN_4_SLOPE            0.125
/* Input Port  5 */
#define IN_PORT_5_NAME        H_mav
#define INPUT_5_WIDTH         2
#define INPUT_DIMS_5_COL      1
#define INPUT_5_DTYPE         uint8_T
#define INPUT_5_COMPLEX       COMPLEX_NO
#define IN_5_FRAME_BASED      FRAME_NO
#define IN_5_BUS_BASED        0
#define IN_5_BUS_NAME         
#define IN_5_DIMS             1-D
#define INPUT_5_FEEDTHROUGH   1
#define IN_5_ISSIGNED         0
#define IN_5_WORDLENGTH       8
#define IN_5_FIXPOINTSCALING  1
#define IN_5_FRACTIONLENGTH   9
#define IN_5_BIAS             0
#define IN_5_SLOPE            0.125
/* Input Port  6 */
#define IN_PORT_6_NAME        H_data_to_AIR_RX
#define INPUT_6_WIDTH         4
#define INPUT_DIMS_6_COL      1
#define INPUT_6_DTYPE         uint8_T
#define INPUT_6_COMPLEX       COMPLEX_NO
#define IN_6_FRAME_BASED      FRAME_NO
#define IN_6_BUS_BASED        0
#define IN_6_BUS_NAME         
#define IN_6_DIMS             1-D
#define INPUT_6_FEEDTHROUGH   1
#define IN_6_ISSIGNED         0
#define IN_6_WORDLENGTH       8
#define IN_6_FIXPOINTSCALING  1
#define IN_6_FRACTIONLENGTH   9
#define IN_6_BIAS             0
#define IN_6_SLOPE            0.125
/* Input Port  7 */
#define IN_PORT_7_NAME        Base_mode_to_SF
#define INPUT_7_WIDTH         1
#define INPUT_DIMS_7_COL      1
#define INPUT_7_DTYPE         uint8_T
#define INPUT_7_COMPLEX       COMPLEX_NO
#define IN_7_FRAME_BASED      FRAME_NO
#define IN_7_BUS_BASED        0
#define IN_7_BUS_NAME         
#define IN_7_DIMS             1-D
#define INPUT_7_FEEDTHROUGH   1
#define IN_7_ISSIGNED         0
#define IN_7_WORDLENGTH       8
#define IN_7_FIXPOINTSCALING  1
#define IN_7_FRACTIONLENGTH   9
#define IN_7_BIAS             0
#define IN_7_SLOPE            0.125

#define NUM_OUTPUTS           18
/* Output Port  0 */
#define OUT_PORT_0_NAME       Heartbeat_data
#define OUTPUT_0_WIDTH        4
#define OUTPUT_DIMS_0_COL     1
#define OUTPUT_0_DTYPE        uint8_T
#define OUTPUT_0_COMPLEX      COMPLEX_NO
#define OUT_0_FRAME_BASED     FRAME_NO
#define OUT_0_BUS_BASED       0
#define OUT_0_BUS_NAME        
#define OUT_0_DIMS            1-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125
/* Output Port  1 */
#define OUT_PORT_1_NAME       Heartbeat_custom
#define OUTPUT_1_WIDTH        1
#define OUTPUT_DIMS_1_COL     1
#define OUTPUT_1_DTYPE        uint32_T
#define OUTPUT_1_COMPLEX      COMPLEX_NO
#define OUT_1_FRAME_BASED     FRAME_NO
#define OUT_1_BUS_BASED       0
#define OUT_1_BUS_NAME        
#define OUT_1_DIMS            1-D
#define OUT_1_ISSIGNED        1
#define OUT_1_WORDLENGTH      8
#define OUT_1_FIXPOINTSCALING 1
#define OUT_1_FRACTIONLENGTH  3
#define OUT_1_BIAS            0
#define OUT_1_SLOPE           0.125
/* Output Port  2 */
#define OUT_PORT_2_NAME       Mav_state
#define OUTPUT_2_WIDTH        1
#define OUTPUT_DIMS_2_COL     1
#define OUTPUT_2_DTYPE        uint8_T
#define OUTPUT_2_COMPLEX      COMPLEX_NO
#define OUT_2_FRAME_BASED     FRAME_NO
#define OUT_2_BUS_BASED       0
#define OUT_2_BUS_NAME        
#define OUT_2_DIMS            1-D
#define OUT_2_ISSIGNED        1
#define OUT_2_WORDLENGTH      8
#define OUT_2_FIXPOINTSCALING 1
#define OUT_2_FRACTIONLENGTH  3
#define OUT_2_BIAS            0
#define OUT_2_SLOPE           0.125
/* Output Port  3 */
#define OUT_PORT_3_NAME       int_sw_safe_interv
#define OUTPUT_3_WIDTH        2
#define OUTPUT_DIMS_3_COL     1
#define OUTPUT_3_DTYPE        uint8_T
#define OUTPUT_3_COMPLEX      COMPLEX_NO
#define OUT_3_FRAME_BASED     FRAME_NO
#define OUT_3_BUS_BASED       0
#define OUT_3_BUS_NAME        
#define OUT_3_DIMS            1-D
#define OUT_3_ISSIGNED        1
#define OUT_3_WORDLENGTH      8
#define OUT_3_FIXPOINTSCALING 1
#define OUT_3_FRACTIONLENGTH  3
#define OUT_3_BIAS            0
#define OUT_3_SLOPE           0.125
/* Output Port  4 */
#define OUT_PORT_4_NAME       Cal_home
#define OUTPUT_4_WIDTH        3
#define OUTPUT_DIMS_4_COL     1
#define OUTPUT_4_DTYPE        uint8_T
#define OUTPUT_4_COMPLEX      COMPLEX_NO
#define OUT_4_FRAME_BASED     FRAME_NO
#define OUT_4_BUS_BASED       0
#define OUT_4_BUS_NAME        
#define OUT_4_DIMS            1-D
#define OUT_4_ISSIGNED        1
#define OUT_4_WORDLENGTH      8
#define OUT_4_FIXPOINTSCALING 1
#define OUT_4_FRACTIONLENGTH  3
#define OUT_4_BIAS            0
#define OUT_4_SLOPE           0.125
/* Output Port  5 */
#define OUT_PORT_5_NAME       Base_mode
#define OUTPUT_5_WIDTH        1
#define OUTPUT_DIMS_5_COL     1
#define OUTPUT_5_DTYPE        uint8_T
#define OUTPUT_5_COMPLEX      COMPLEX_NO
#define OUT_5_FRAME_BASED     FRAME_NO
#define OUT_5_BUS_BASED       0
#define OUT_5_BUS_NAME        
#define OUT_5_DIMS            1-D
#define OUT_5_ISSIGNED        1
#define OUT_5_WORDLENGTH      8
#define OUT_5_FIXPOINTSCALING 1
#define OUT_5_FRACTIONLENGTH  3
#define OUT_5_BIAS            0
#define OUT_5_SLOPE           0.125
/* Output Port  6 */
#define OUT_PORT_6_NAME       GC_request
#define OUTPUT_6_WIDTH        2
#define OUTPUT_DIMS_6_COL     1
#define OUTPUT_6_DTYPE        uint16_T
#define OUTPUT_6_COMPLEX      COMPLEX_NO
#define OUT_6_FRAME_BASED     FRAME_NO
#define OUT_6_BUS_BASED       0
#define OUT_6_BUS_NAME        
#define OUT_6_DIMS            1-D
#define OUT_6_ISSIGNED        1
#define OUT_6_WORDLENGTH      8
#define OUT_6_FIXPOINTSCALING 1
#define OUT_6_FRACTIONLENGTH  3
#define OUT_6_BIAS            0
#define OUT_6_SLOPE           0.125
/* Output Port  7 */
#define OUT_PORT_7_NAME       P_value_change
#define OUTPUT_7_WIDTH        1
#define OUTPUT_DIMS_7_COL     1
#define OUTPUT_7_DTYPE        real_T
#define OUTPUT_7_COMPLEX      COMPLEX_NO
#define OUT_7_FRAME_BASED     FRAME_NO
#define OUT_7_BUS_BASED       0
#define OUT_7_BUS_NAME        
#define OUT_7_DIMS            1-D
#define OUT_7_ISSIGNED        1
#define OUT_7_WORDLENGTH      8
#define OUT_7_FIXPOINTSCALING 1
#define OUT_7_FRACTIONLENGTH  3
#define OUT_7_BIAS            0
#define OUT_7_SLOPE           0.125
/* Output Port  8 */
#define OUT_PORT_8_NAME       WP_info
#define OUTPUT_8_WIDTH        6
#define OUTPUT_DIMS_8_COL     1
#define OUTPUT_8_DTYPE        uint16_T
#define OUTPUT_8_COMPLEX      COMPLEX_NO
#define OUT_8_FRAME_BASED     FRAME_NO
#define OUT_8_BUS_BASED       0
#define OUT_8_BUS_NAME        
#define OUT_8_DIMS            1-D
#define OUT_8_ISSIGNED        1
#define OUT_8_WORDLENGTH      8
#define OUT_8_FIXPOINTSCALING 1
#define OUT_8_FRACTIONLENGTH  3
#define OUT_8_BIAS            0
#define OUT_8_SLOPE           0.125
/* Output Port  9 */
#define OUT_PORT_9_NAME       WP_param
#define OUTPUT_9_WIDTH        7
#define OUTPUT_DIMS_9_COL     1
#define OUTPUT_9_DTYPE        real_T
#define OUTPUT_9_COMPLEX      COMPLEX_NO
#define OUT_9_FRAME_BASED     FRAME_NO
#define OUT_9_BUS_BASED       0
#define OUT_9_BUS_NAME        
#define OUT_9_DIMS            1-D
#define OUT_9_ISSIGNED        1
#define OUT_9_WORDLENGTH      8
#define OUT_9_FIXPOINTSCALING 1
#define OUT_9_FRACTIONLENGTH  3
#define OUT_9_BIAS            0
#define OUT_9_SLOPE           0.125
/* Output Port  10 */
#define OUT_PORT_10_NAME       mem_out
#define OUTPUT_10_WIDTH        8
#define OUTPUT_DIMS_10_COL     1
#define OUTPUT_10_DTYPE        uint16_T
#define OUTPUT_10_COMPLEX      COMPLEX_NO
#define OUT_10_FRAME_BASED     FRAME_NO
#define OUT_10_BUS_BASED       0
#define OUT_10_BUS_NAME        
#define OUT_10_DIMS            1-D
#define OUT_10_ISSIGNED        1
#define OUT_10_WORDLENGTH      8
#define OUT_10_FIXPOINTSCALING 1
#define OUT_10_FRACTIONLENGTH  3
#define OUT_10_BIAS            0
#define OUT_10_SLOPE           0.125
/* Output Port  11 */
#define OUT_PORT_11_NAME       T_number
#define OUTPUT_11_WIDTH        1
#define OUTPUT_DIMS_11_COL     1
#define OUTPUT_11_DTYPE        uint8_T
#define OUTPUT_11_COMPLEX      COMPLEX_NO
#define OUT_11_FRAME_BASED     FRAME_NO
#define OUT_11_BUS_BASED       0
#define OUT_11_BUS_NAME        
#define OUT_11_DIMS            1-D
#define OUT_11_ISSIGNED        1
#define OUT_11_WORDLENGTH      8
#define OUT_11_FIXPOINTSCALING 1
#define OUT_11_FRACTIONLENGTH  3
#define OUT_11_BIAS            0
#define OUT_11_SLOPE           0.125
/* Output Port  12 */
#define OUT_PORT_12_NAME       T_ref
#define OUTPUT_12_WIDTH        1
#define OUTPUT_DIMS_12_COL     1
#define OUTPUT_12_DTYPE        real_T
#define OUTPUT_12_COMPLEX      COMPLEX_NO
#define OUT_12_FRAME_BASED     FRAME_NO
#define OUT_12_BUS_BASED       0
#define OUT_12_BUS_NAME        
#define OUT_12_DIMS            1-D
#define OUT_12_ISSIGNED        1
#define OUT_12_WORDLENGTH      8
#define OUT_12_FIXPOINTSCALING 1
#define OUT_12_FRACTIONLENGTH  3
#define OUT_12_BIAS            0
#define OUT_12_SLOPE           0.125
/* Output Port  13 */
#define OUT_PORT_13_NAME       Cal_alt
#define OUTPUT_13_WIDTH        1
#define OUTPUT_DIMS_13_COL     1
#define OUTPUT_13_DTYPE        uint8_T
#define OUTPUT_13_COMPLEX      COMPLEX_NO
#define OUT_13_FRAME_BASED     FRAME_NO
#define OUT_13_BUS_BASED       0
#define OUT_13_BUS_NAME        
#define OUT_13_DIMS            1-D
#define OUT_13_ISSIGNED        1
#define OUT_13_WORDLENGTH      8
#define OUT_13_FIXPOINTSCALING 1
#define OUT_13_FRACTIONLENGTH  3
#define OUT_13_BIAS            0
#define OUT_13_SLOPE           0.125
/* Output Port  14 */
#define OUT_PORT_14_NAME       T_int
#define OUTPUT_14_WIDTH        1
#define OUTPUT_DIMS_14_COL     1
#define OUTPUT_14_DTYPE        uint8_T
#define OUTPUT_14_COMPLEX      COMPLEX_NO
#define OUT_14_FRAME_BASED     FRAME_NO
#define OUT_14_BUS_BASED       0
#define OUT_14_BUS_NAME        
#define OUT_14_DIMS            1-D
#define OUT_14_ISSIGNED        1
#define OUT_14_WORDLENGTH      8
#define OUT_14_FIXPOINTSCALING 1
#define OUT_14_FRACTIONLENGTH  3
#define OUT_14_BIAS            0
#define OUT_14_SLOPE           0.125
/* Output Port  15 */
#define OUT_PORT_15_NAME       P_int
#define OUTPUT_15_WIDTH        1
#define OUTPUT_DIMS_15_COL     1
#define OUTPUT_15_DTYPE        uint8_T
#define OUTPUT_15_COMPLEX      COMPLEX_NO
#define OUT_15_FRAME_BASED     FRAME_NO
#define OUT_15_BUS_BASED       0
#define OUT_15_BUS_NAME        
#define OUT_15_DIMS            1-D
#define OUT_15_ISSIGNED        1
#define OUT_15_WORDLENGTH      8
#define OUT_15_FIXPOINTSCALING 1
#define OUT_15_FRACTIONLENGTH  3
#define OUT_15_BIAS            0
#define OUT_15_SLOPE           0.125
/* Output Port  16 */
#define OUT_PORT_16_NAME       P_ref
#define OUTPUT_16_WIDTH        1
#define OUTPUT_DIMS_16_COL     1
#define OUTPUT_16_DTYPE        real_T
#define OUTPUT_16_COMPLEX      COMPLEX_NO
#define OUT_16_FRAME_BASED     FRAME_NO
#define OUT_16_BUS_BASED       0
#define OUT_16_BUS_NAME        
#define OUT_16_DIMS            1-D
#define OUT_16_ISSIGNED        1
#define OUT_16_WORDLENGTH      8
#define OUT_16_FIXPOINTSCALING 1
#define OUT_16_FRACTIONLENGTH  3
#define OUT_16_BIAS            0
#define OUT_16_SLOPE           0.125
/* Output Port  17 */
#define OUT_PORT_17_NAME       go_home
#define OUTPUT_17_WIDTH        1
#define OUTPUT_DIMS_17_COL     1
#define OUTPUT_17_DTYPE        uint8_T
#define OUTPUT_17_COMPLEX      COMPLEX_NO
#define OUT_17_FRAME_BASED     FRAME_NO
#define OUT_17_BUS_BASED       0
#define OUT_17_BUS_NAME        
#define OUT_17_DIMS            1-D
#define OUT_17_ISSIGNED        1
#define OUT_17_WORDLENGTH      8
#define OUT_17_FIXPOINTSCALING 1
#define OUT_17_FRACTIONLENGTH  3
#define OUT_17_BIAS            0
#define OUT_17_SLOPE           0.125

#define NPARAMS               0

#define SAMPLE_TIME_0         INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES       0
#define DISC_STATES_IC        [0]
#define NUM_CONT_STATES       0
#define CONT_STATES_IC        [0]

#define SFUNWIZ_GENERATE_TLC  1
#define SOURCEFILES           "__SFB__"
#define PANELINDEX            N/A
#define USE_SIMSTRUCT         0
#define SHOW_COMPILE_STEPS    0
#define CREATE_DEBUG_MEXFILE  0
#define SAVE_CODE_ONLY        1
#define SFUNWIZ_REVISION      3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"


extern void receive_MAVLink_v4_6_beta_AL_HITL_HOME_sfun_Start_wrapper(void);
extern void receive_MAVLink_v4_6_beta_AL_HITL_HOME_sfun_Outputs_wrapper(const uint8_T *bytes_in,
			const int32_T *len_in,
			const uint16_T *count,
			const uint8_T *AP_SI,
			const uint16_T *mem_in,
			const uint8_T *H_mav,
			const uint8_T *H_data_to_AIR_RX,
			const uint8_T *Base_mode_to_SF,
			uint8_T *Heartbeat_data,
			uint32_T *Heartbeat_custom,
			uint8_T *Mav_state,
			uint8_T *int_sw_safe_interv,
			uint8_T *Cal_home,
			uint8_T *Base_mode,
			uint16_T *GC_request,
			real_T *P_value_change,
			uint16_T *WP_info,
			real_T *WP_param,
			uint16_T *mem_out,
			uint8_T *T_number,
			real_T *T_ref,
			uint8_T *Cal_alt,
			uint8_T *T_int,
			uint8_T *P_int,
			real_T *P_ref,
			uint8_T *go_home,
			const int_T u_width);
/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{

    DECL_AND_INIT_DIMSINFO(inputDimsInfo);
    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return; /* Parameter mismatch will be reported by Simulink */
    }

    ssSetArrayLayoutForCodeGen(S, SS_COLUMN_MAJOR);

    ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);


    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;
    /* Input Port 0 */
    ssSetInputPortWidth(S, 0, INPUT_0_WIDTH);
    ssSetInputPortDataType(S, 0, SS_UINT8);
    ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 0, 1); /*direct input signal access*/

    /* Input Port 1 */
    ssSetInputPortWidth(S, 1, INPUT_1_WIDTH);
    ssSetInputPortDataType(S, 1, SS_INT32);
    ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 1, 1); /*direct input signal access*/

    /* Input Port 2 */
    ssSetInputPortWidth(S, 2, INPUT_2_WIDTH);
    ssSetInputPortDataType(S, 2, SS_UINT16);
    ssSetInputPortComplexSignal(S, 2, INPUT_2_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 2, 1); /*direct input signal access*/

    /* Input Port 3 */
    ssSetInputPortWidth(S, 3, INPUT_3_WIDTH);
    ssSetInputPortDataType(S, 3, SS_UINT8);
    ssSetInputPortComplexSignal(S, 3, INPUT_3_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 3, INPUT_3_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 3, 1); /*direct input signal access*/

    /* Input Port 4 */
    ssSetInputPortWidth(S, 4, INPUT_4_WIDTH);
    ssSetInputPortDataType(S, 4, SS_UINT16);
    ssSetInputPortComplexSignal(S, 4, INPUT_4_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 4, INPUT_4_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 4, 1); /*direct input signal access*/

    /* Input Port 5 */
    ssSetInputPortWidth(S, 5, INPUT_5_WIDTH);
    ssSetInputPortDataType(S, 5, SS_UINT8);
    ssSetInputPortComplexSignal(S, 5, INPUT_5_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 5, INPUT_5_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 5, 1); /*direct input signal access*/

    /* Input Port 6 */
    ssSetInputPortWidth(S, 6, INPUT_6_WIDTH);
    ssSetInputPortDataType(S, 6, SS_UINT8);
    ssSetInputPortComplexSignal(S, 6, INPUT_6_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 6, INPUT_6_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 6, 1); /*direct input signal access*/

    /* Input Port 7 */
    ssSetInputPortWidth(S, 7, INPUT_7_WIDTH);
    ssSetInputPortDataType(S, 7, SS_UINT8);
    ssSetInputPortComplexSignal(S, 7, INPUT_7_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 7, INPUT_7_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 7, 1); /*direct input signal access*/


    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    /* Output Port 0 */
    ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
    ssSetOutputPortDataType(S, 0, SS_UINT8);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
    /* Output Port 1 */
    ssSetOutputPortWidth(S, 1, OUTPUT_1_WIDTH);
    ssSetOutputPortDataType(S, 1, SS_UINT32);
    ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);
    /* Output Port 2 */
    ssSetOutputPortWidth(S, 2, OUTPUT_2_WIDTH);
    ssSetOutputPortDataType(S, 2, SS_UINT8);
    ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);
    /* Output Port 3 */
    ssSetOutputPortWidth(S, 3, OUTPUT_3_WIDTH);
    ssSetOutputPortDataType(S, 3, SS_UINT8);
    ssSetOutputPortComplexSignal(S, 3, OUTPUT_3_COMPLEX);
    /* Output Port 4 */
    ssSetOutputPortWidth(S, 4, OUTPUT_4_WIDTH);
    ssSetOutputPortDataType(S, 4, SS_UINT8);
    ssSetOutputPortComplexSignal(S, 4, OUTPUT_4_COMPLEX);
    /* Output Port 5 */
    ssSetOutputPortWidth(S, 5, OUTPUT_5_WIDTH);
    ssSetOutputPortDataType(S, 5, SS_UINT8);
    ssSetOutputPortComplexSignal(S, 5, OUTPUT_5_COMPLEX);
    /* Output Port 6 */
    ssSetOutputPortWidth(S, 6, OUTPUT_6_WIDTH);
    ssSetOutputPortDataType(S, 6, SS_UINT16);
    ssSetOutputPortComplexSignal(S, 6, OUTPUT_6_COMPLEX);
    /* Output Port 7 */
    ssSetOutputPortWidth(S, 7, OUTPUT_7_WIDTH);
    ssSetOutputPortDataType(S, 7, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 7, OUTPUT_7_COMPLEX);
    /* Output Port 8 */
    ssSetOutputPortWidth(S, 8, OUTPUT_8_WIDTH);
    ssSetOutputPortDataType(S, 8, SS_UINT16);
    ssSetOutputPortComplexSignal(S, 8, OUTPUT_8_COMPLEX);
    /* Output Port 9 */
    ssSetOutputPortWidth(S, 9, OUTPUT_9_WIDTH);
    ssSetOutputPortDataType(S, 9, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 9, OUTPUT_9_COMPLEX);
    /* Output Port 10 */
    ssSetOutputPortWidth(S, 10, OUTPUT_10_WIDTH);
    ssSetOutputPortDataType(S, 10, SS_UINT16);
    ssSetOutputPortComplexSignal(S, 10, OUTPUT_10_COMPLEX);
    /* Output Port 11 */
    ssSetOutputPortWidth(S, 11, OUTPUT_11_WIDTH);
    ssSetOutputPortDataType(S, 11, SS_UINT8);
    ssSetOutputPortComplexSignal(S, 11, OUTPUT_11_COMPLEX);
    /* Output Port 12 */
    ssSetOutputPortWidth(S, 12, OUTPUT_12_WIDTH);
    ssSetOutputPortDataType(S, 12, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 12, OUTPUT_12_COMPLEX);
    /* Output Port 13 */
    ssSetOutputPortWidth(S, 13, OUTPUT_13_WIDTH);
    ssSetOutputPortDataType(S, 13, SS_UINT8);
    ssSetOutputPortComplexSignal(S, 13, OUTPUT_13_COMPLEX);
    /* Output Port 14 */
    ssSetOutputPortWidth(S, 14, OUTPUT_14_WIDTH);
    ssSetOutputPortDataType(S, 14, SS_UINT8);
    ssSetOutputPortComplexSignal(S, 14, OUTPUT_14_COMPLEX);
    /* Output Port 15 */
    ssSetOutputPortWidth(S, 15, OUTPUT_15_WIDTH);
    ssSetOutputPortDataType(S, 15, SS_UINT8);
    ssSetOutputPortComplexSignal(S, 15, OUTPUT_15_COMPLEX);
    /* Output Port 16 */
    ssSetOutputPortWidth(S, 16, OUTPUT_16_WIDTH);
    ssSetOutputPortDataType(S, 16, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 16, OUTPUT_16_COMPLEX);
    /* Output Port 17 */
    ssSetOutputPortWidth(S, 17, OUTPUT_17_WIDTH);
    ssSetOutputPortDataType(S, 17, SS_UINT8);
    ssSetOutputPortComplexSignal(S, 17, OUTPUT_17_COMPLEX);
    ssSetNumPWork(S, 0);

    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    ssSetSimulinkVersionGeneratedIn(S, "10.2");

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                     SS_OPTION_USE_TLC_WITH_ACCELERATOR |
                     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

#if defined(MATLAB_MEX_FILE)
#define MDL_SET_INPUT_PORT_WIDTH
static void mdlSetInputPortWidth(SimStruct *S, int_T port,
                                 int_T inputPortWidth)
{
    ssSetInputPortWidth(S, port, inputPortWidth);
}
#define MDL_SET_OUTPUT_PORT_WIDTH
static void mdlSetOutputPortWidth(SimStruct *S, int_T port,
                                  int_T outputPortWidth)
{
    ssSetOutputPortWidth(S, port, ssGetInputPortWidth(S, 0));
}
#endif
/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetModelReferenceSampleTimeDefaultInheritance(S);
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE
static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
    ssSetInputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_START  /* Change to #undef to remove function */
#if defined(MDL_START)
/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{

    receive_MAVLink_v4_6_beta_AL_HITL_HOME_sfun_Start_wrapper();
}
#endif /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
    const uint8_T *bytes_in = (uint8_T *) ssGetInputPortRealSignal(S, 0);
    const int32_T *len_in = (int32_T *) ssGetInputPortRealSignal(S, 1);
    const uint16_T *count = (uint16_T *) ssGetInputPortRealSignal(S, 2);
    const uint8_T *AP_SI = (uint8_T *) ssGetInputPortRealSignal(S, 3);
    const uint16_T *mem_in = (uint16_T *) ssGetInputPortRealSignal(S, 4);
    const uint8_T *H_mav = (uint8_T *) ssGetInputPortRealSignal(S, 5);
    const uint8_T *H_data_to_AIR_RX = (uint8_T *) ssGetInputPortRealSignal(S, 6);
    const uint8_T *Base_mode_to_SF = (uint8_T *) ssGetInputPortRealSignal(S, 7);
    uint8_T *Heartbeat_data = (uint8_T *) ssGetOutputPortRealSignal(S, 0);
    uint32_T *Heartbeat_custom = (uint32_T *) ssGetOutputPortRealSignal(S, 1);
    uint8_T *Mav_state = (uint8_T *) ssGetOutputPortRealSignal(S, 2);
    uint8_T *int_sw_safe_interv = (uint8_T *) ssGetOutputPortRealSignal(S, 3);
    uint8_T *Cal_home = (uint8_T *) ssGetOutputPortRealSignal(S, 4);
    uint8_T *Base_mode = (uint8_T *) ssGetOutputPortRealSignal(S, 5);
    uint16_T *GC_request = (uint16_T *) ssGetOutputPortRealSignal(S, 6);
    real_T *P_value_change = (real_T *) ssGetOutputPortRealSignal(S, 7);
    uint16_T *WP_info = (uint16_T *) ssGetOutputPortRealSignal(S, 8);
    real_T *WP_param = (real_T *) ssGetOutputPortRealSignal(S, 9);
    uint16_T *mem_out = (uint16_T *) ssGetOutputPortRealSignal(S, 10);
    uint8_T *T_number = (uint8_T *) ssGetOutputPortRealSignal(S, 11);
    real_T *T_ref = (real_T *) ssGetOutputPortRealSignal(S, 12);
    uint8_T *Cal_alt = (uint8_T *) ssGetOutputPortRealSignal(S, 13);
    uint8_T *T_int = (uint8_T *) ssGetOutputPortRealSignal(S, 14);
    uint8_T *P_int = (uint8_T *) ssGetOutputPortRealSignal(S, 15);
    real_T *P_ref = (real_T *) ssGetOutputPortRealSignal(S, 16);
    uint8_T *go_home = (uint8_T *) ssGetOutputPortRealSignal(S, 17);
    const int_T u_width = ssGetInputPortWidth(S, 0);

    receive_MAVLink_v4_6_beta_AL_HITL_HOME_sfun_Outputs_wrapper(bytes_in, len_in, count, AP_SI, mem_in, H_mav, H_data_to_AIR_RX, Base_mode_to_SF, Heartbeat_data, Heartbeat_custom, Mav_state, int_sw_safe_interv, Cal_home, Base_mode, GC_request, P_value_change, WP_info, WP_param, mem_out, T_number, T_ref, Cal_alt, T_int, P_int, P_ref, go_home, u_width);

}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{

}


#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif



